// web/src/lib/character-selector/copy.ts
// Every visible and spoken string of the nav character selector, verbatim from section 6 of
// design/specs/2026-10-09-nav-character-selector.md. One module so a wording change is one edit.
export const selectorCopy = {
  listHeading: 'Your characters',
  manage: 'Manage',
  manageHref: '/account#characters',
  signedOutHeading: 'Add your character',
  closedSignedOut: 'Sign in',
  closedSignedOutSub: 'or paste an export',
  signedOutAria: 'Sign in or choose a character',
  /** The label of the sheet and popover dialog. */
  dialogLabel: 'Choose a character',
  close: 'Close',
  filterPlaceholder: 'Filter by name',
  filterLabel: 'Filter characters by name',
  pasteTitle: 'Paste an export',
  pasteSub: 'From the addon. Adds a character to this list.',
  pasteLabel: 'Addon export',
  pastePlaceholder: 'Paste the export here',
  pasteUse: 'Use this character',
  pasteCancel: 'Cancel',
  pasteInvalid: 'That is not a Forever Sixty export.',
  addonTitle: 'Get the addon',
  addonSub: 'Export a character from the game.',
  addonHref: '/setup',
  signInTitle: 'Sign in',
  signInSub: 'Email or Battle.net. Keeps your characters.',
  signInHref: '/login',
  noneTitle: 'No characters yet.',
  noneBody: 'Paste an export from the addon to add one.',
  loadErrorTitle: 'Your characters did not load.',
  loadErrorBody: 'Check your connection and try again. You can still paste an export.',
  tryAgain: 'Try again',
  sessionEnded: 'Your session ended. Sign in to see your other characters.',
  pastedNotSaved: 'Not saved to an account. Sign in to keep it.',
  retry: 'Retry',
  retrying: 'Trying',
  refreshing: 'Refreshing from Battle.net',
  staleAddonTail: 'Log in to the game to update',
  staleBnetTail: 'Refresh from your account',
  staleBnetHref: '/account',
  sourceAddon: 'Addon',
  sourceBnet: 'Battle.net',
  sourcePasted: 'Pasted export',
  discord: 'Discord',
  menuSignInSub: 'or paste an export',
  failedLine: (age: string): string => `Battle.net refresh failed · last good ${age}`,
  markTooltip: {
    stale: (age: string): string => `Last synced ${age}. Log in to the game to update.`,
    failed: 'Battle.net refresh failed. Showing the last good data.',
    session: 'Signed out. Sign in to see your other characters.',
  },
  markAria: {
    stale: 'Sync is stale.',
    failed: 'Sync failed.',
    session: 'Signed out.',
  },
  nowUsing: (name: string): string => `Now using ${name}.`,
} as const;
