package adapter

import (
	"embed"
	"fmt"

	"github.com/wowsims/classic/sim/core/proto"
	googleproto "google.golang.org/protobuf/proto"
)

//go:embed testdata/*.result.pb
var fixtures embed.FS

// Fixture returns a checked-in engine result for a spec. The api lane's
// validation and execution-score tests use it so they need no engine
// binary; the golden tests below use it as their input.
//
// Regenerated by running testdata/<spec>.request.json through
// sim/cmd/forever-sim; golden_test.go's header has the procedure.
func Fixture(spec string) (*proto.RaidSimResult, error) {
	b, err := fixtures.ReadFile("testdata/" + spec + ".result.pb")
	if err != nil {
		return nil, fmt.Errorf("adapter: no fixture for spec %q: %w", spec, err)
	}
	res := &proto.RaidSimResult{}
	if err := googleproto.Unmarshal(b, res); err != nil {
		return nil, fmt.Errorf("adapter: fixture for %q is corrupt: %w", spec, err)
	}
	return res, nil
}
