# Repository-level targets. Each module keeps its own tooling; this file is
# only for things that cross a module boundary.
#
# Two of them cross into the engine fork, and they do DIFFERENT things:
#
#   engine-pin  writes sim/enginever/version.go - the engine's short sha -
#               and nothing else. It reads the fork; it never writes to it.
#   apl-sync    copies each curated rotation into the fork's
#               ui/<class>/apls/ and into sim/request/apl/. It writes
#               rotations; it never touches the pin.
#
# Believing engine-pin carried rotations across is how two copies of a
# rotation drifted, so neither target does the other's job and apl-check
# proves the copies.

# Where the engine fork is checked out. Override for a different location:
#   make engine-pin ENGINE_DIR=/somewhere/else
ENGINE_DIR ?= /Users/jh/code/wowsims-forever

.PHONY: engine-pin
# engine-pin writes sim/enginever/version.go from the engine checkout's HEAD -
# ONLY that file. It does not copy rotations, presets or anything else into or
# out of the fork; `apl-sync` below is what carries rotations.
# This is the only way that file is ever written. ENGINE_VERSION is the short
# sha, and it names the wasm artifact directory, the premium image tag, and
# every stored sim and validation row, so pinning a dirty tree would produce
# a version string that identifies nothing. Hence the cleanliness check.
engine-pin:
	@test -d "$(ENGINE_DIR)/.git" || { echo "no engine checkout at $(ENGINE_DIR); set ENGINE_DIR"; exit 1; }
	@if [ -n "$$(git -C "$(ENGINE_DIR)" status --porcelain)" ]; then \
	  echo "engine checkout at $(ENGINE_DIR) is dirty; commit or stash before pinning"; exit 1; \
	fi
	@sha=$$(git -C "$(ENGINE_DIR)" rev-parse --short HEAD); \
	mkdir -p sim/enginever; \
	printf '// Code generated by "make engine-pin". DO NOT EDIT.\n\npackage enginever\n\n// Version is the short commit sha of wowsims-forever that sim.wasm, sim.js\n// and the forever-sim binary were built from. It names the immutable wasm\n// directory, the premium lane image tag, and every stored sim row.\nconst Version = "%s"\n' "$$sha" > sim/enginever/version.go; \
	gofmt -w sim/enginever/version.go; \
	if grep -q '%' sim/enginever/version.go; then \
	  echo "engine-pin: sim/enginever/version.go still contains a literal percent sign - the printf substitution failed"; exit 1; \
	fi; \
	echo "pinned engine version $$sha"

ARTIFACT_DIR ?= artifacts
# The design's browser download budget, gzipped. The same number gates
# `make artifacts` and the sim workflow's artifact job.
WASM_BUDGET_MB = 4
WEB_SIM_DIR   = web/public/_sim
ACTIVE_BUILD_JSON = web/src/data/active-build.json
SIMDB_EMBED   = sim/internal/simdb/simdb.bin
# Read at parse time so the copy below has a real prerequisite: an earlier
# version depended on active-build.json alone, and regenerating the build's
# simdb.bin left the embedded copy stale while make reported nothing to do.
ACTIVE_BUILD  = $(shell sed -n 's/.*"build"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' $(ACTIVE_BUILD_JSON) 2>/dev/null)
SIMDB_SRC     = data/builds/$(ACTIVE_BUILD)/simdb.bin

.PHONY: simdb
# simdb copies the ACTIVE build's item database where sim/internal/simdb
# embeds it. Forever re-itemises, so the engine's own --tags=with_db
# table - vanilla's - resolves almost none of a Forever gear set; this
# file is what makes an item id mean something in both artifacts.
#
# The build is read from web/src/data/active-build.json and never typed
# in, so switching builds is one edit in one place. The copy is
# git-ignored; data/builds/<build>/simdb.bin is what is committed.
#
# Every `go build`, `go test` and `go vet` in sim/ needs this file,
# because //go:embed resolves at compile time. Run `make simdb` once
# after a fresh clone.
simdb: simdb-check $(SIMDB_EMBED)

.PHONY: simdb-check
# The diagnostics have to live in a phony target that runs BEFORE the
# file rule. Inside the recipe they are unreachable: a missing source is
# a prerequisite with no rule, so make refuses the target during
# resolution - "No rule to make target data/builds//simdb.bin" - and the
# recipe, guards and all, never runs. Depend on `simdb`, not on
# $(SIMDB_EMBED), to get them.
simdb-check:
	@test -n "$(ACTIVE_BUILD)" || { \
	  echo "$(ACTIVE_BUILD_JSON) names no build"; exit 1; }
	@test -f "$(SIMDB_SRC)" || { \
	  echo "no $(SIMDB_SRC); the data lane's \`python -m pipeline simdb\` has not run for build $(ACTIVE_BUILD)"; exit 1; }

$(SIMDB_EMBED): $(SIMDB_SRC) $(ACTIVE_BUILD_JSON)
	@mkdir -p $(dir $(SIMDB_EMBED))
	@cp "$(SIMDB_SRC)" $(SIMDB_EMBED)
	@echo "embedded $(SIMDB_SRC) ($$(wc -c < $(SIMDB_EMBED) | tr -d ' ') bytes)"

.PHONY: artifacts
# artifacts builds the two things one pinned engine sha produces, both
# from the sim/ module: sim.wasm + sim.js for the browser, and
# forever-sim for the server lane. The engine repository ships no
# artifact of ours; it stays a clean upstreamable library.
#
# Neither is built --tags=with_db. That tag carries the engine's own
# vanilla item table, which Forever re-itemises out from under; both
# artifacts embed the active build's simdb.bin instead, which is what
# `simdb` above puts in place and what sim/internal/simdb loads.
#
# NOT a prerequisite here: engine-pin. It writes sim/enginever/version.go
# from a LOCAL checkout at ENGINE_DIR, which does not exist on a CI
# runner -- web.yml's deploy job builds these same artifacts for
# publish-wasm below with sim/go.mod's replace already rewritten by
# .github/actions/pin-engine (no local checkout needed) and
# sim/enginever/version.go already committed. Forcing engine-pin here
# would fail that build and, locally, would refuse a dirty engine
# checkout on every `make artifacts` even when nobody meant to move the
# pin. Bump the pin on purpose with `make engine-pin`, then build.
artifacts: simdb
	@mkdir -p $(ARTIFACT_DIR)
#	Each build runs in its OWN subshell. An earlier draft chained two
#	`cd sim` in one shell with `; \`, so the second ran from inside
#	sim/ and failed, and the native binary was silently never built
#	while the recipe reported success.
#	No -ldflags -X: both mains import sim/enginever, so the pin is
#	compiled in and a plain `go build ./cmd/forever-sim` produces a
#	binary that knows its own engine rather than one stamped "dev".
	@(cd sim && GOOS=js GOARCH=wasm go build -o ../$(ARTIFACT_DIR)/sim.wasm ./cmd/wasm) && \
	  (cd sim && go build -ldflags="-s -w" -o ../$(ARTIFACT_DIR)/forever-sim ./cmd/forever-sim)
#	install, not cp: wasm_exec.js is read-only inside GOROOT, so a plain
#	cp copies the mode too and the NEXT `make artifacts` dies with
#	"Permission denied" on its own output.
	@install -m 0644 "$$(go env GOROOT)/lib/wasm/wasm_exec.js" $(ARTIFACT_DIR)/sim.js
	@(cd $(ARTIFACT_DIR) && shasum -a 256 sim.wasm sim.js forever-sim > SHA256SUMS)
	@test -x $(ARTIFACT_DIR)/forever-sim || { echo "forever-sim was not built"; exit 1; }
	@ls -l $(ARTIFACT_DIR)
#	The budget is ENFORCED here, not only printed: CI gated it while the
#	Makefile reported it, so a local build could sail past the size the
#	pipeline would refuse and nobody found out until the push.
	@bytes=$$(gzip -9 -c $(ARTIFACT_DIR)/sim.wasm | wc -c | tr -d ' '); \
	awk -v b="$$bytes" 'BEGIN { printf "sim.wasm gzipped: %.2f MB (budget %.2f, engine-only baseline 3.31)\n", b/1048576, $(WASM_BUDGET_MB) }'; \
	awk -v b="$$bytes" 'BEGIN { exit (b <= $(WASM_BUDGET_MB)*1048576) ? 0 : 1 }' || { \
	  echo "sim.wasm is over the $(WASM_BUDGET_MB) MB gzipped budget"; exit 1; }

.PHONY: publish-wasm
# publish-wasm puts the browser pair where the web loads them, under the
# engine version, cached immutably so a new version never collides with a
# cached old one.
publish-wasm: artifacts
#	The binary is asked what engine it is, rather than the generated
#	file being scraped a second time: one answer, from the artifact
#	itself, so the directory can never name a sha the wasm is not.
	@sha=$$(./$(ARTIFACT_DIR)/forever-sim -version); \
	test -n "$$sha" || { echo "forever-sim -version printed nothing"; exit 1; }; \
	mkdir -p "$(WEB_SIM_DIR)/$$sha"; \
	cp $(ARTIFACT_DIR)/sim.wasm $(ARTIFACT_DIR)/sim.js "$(WEB_SIM_DIR)/$$sha/"; \
	echo "published to $(WEB_SIM_DIR)/$$sha"

CURATED_APL_DIR = data/curated/apl
CURATED_SPECS_JSON = data/curated/specs.json

.PHONY: apl-sync
# apl-sync copies every WRITTEN curated rotation into the two places that
# run one. data/curated/apl/<spec>.json's `rotation` block is the single
# source; the engine fork's ui/<class>/apls/forever_<spec>.apl.json is the
# copy the fork's own spec tests run, and sim/request/apl/<spec>.apl.json
# is the copy both artifacts embed. A spec still marked `unwritten` is a
# placeholder and is skipped - copying it would hand the engine an empty
# priority list.
#
# The copy is the curated BYTES, dedented one level, not a re-print of the
# parsed value: the curated file's own layout keeps a short object on one
# line and expands a long one, and no two JSON printers agree on where
# that line falls, so re-printing would churn the fork's tree on
# formatting alone. Syncing an unchanged rotation therefore writes
# nothing, and the fork stays clean enough to pin.
#
# This target WRITES INTO THE FORK. It is the only thing here that does.
# Run `make apl-check` after it, and commit the fork's side there.
apl-sync:
	@test -d "$(ENGINE_DIR)" || { echo "no engine checkout at $(ENGINE_DIR); set ENGINE_DIR"; exit 1; }
	@ENGINE_DIR="$(ENGINE_DIR)" CURATED_APL_DIR="$(CURATED_APL_DIR)" \
	  CURATED_SPECS_JSON="$(CURATED_SPECS_JSON)" python3 tools/apl_sync.py

.PHONY: apl-check
# apl-check holds both derived copies to the curated one. It is what makes
# apl-sync's output a rule rather than a habit: a written spec missing a
# copy, a copy whose content drifted, or a fork copy whose curated source
# went away all fail here, in CI as well as locally.
#
# The comparison is of PARSED json, not bytes: what the copies must agree
# on is the rotation.
#
# ENGINE_DIR is the engine checkout, as for engine-pin.
apl-check:
	@test -d "$(ENGINE_DIR)" || { echo "no engine checkout at $(ENGINE_DIR); set ENGINE_DIR"; exit 1; }
	@ENGINE_DIR="$(ENGINE_DIR)" CURATED_APL_DIR="$(CURATED_APL_DIR)" \
	  CURATED_SPECS_JSON="$(CURATED_SPECS_JSON)" python3 tools/apl_check.py

.PHONY: loot
# loot regenerates the ACTIVE build's Droptimizer and Top Gear data:
# loot.json, enchants.json, suffixes.json, and items.json's `suffixes`
# column. Nothing in a DB2 export says which boss drops an item, so the
# engine fork's own assets/database/db.json is the only source for it,
# and this is the only target that reads it.
#
# Two prerequisites the target cannot supply itself:
#   * the build's raw/ CSVs (Map.csv for the instance types,
#     ItemSparse.csv for the PvP ranks), the same as `python -m pipeline
#     simdb` -- run `python -m pipeline fetch` for the build first;
#   * an engine checkout at ENGINE_DIR, as for engine-pin and apl-sync.
#
# ENGINE_DIR goes through `abspath` because the recipe runs from data/
# and a relative override would resolve against the wrong root.
loot:
	@test -n "$(ACTIVE_BUILD)" || { echo "$(ACTIVE_BUILD_JSON) names no build"; exit 1; }
	@test -f "$(ENGINE_DIR)/assets/database/db.json" || { \
	  echo "no item database at $(ENGINE_DIR)/assets/database/db.json; set ENGINE_DIR"; exit 1; }
	@test -d "data/builds/$(ACTIVE_BUILD)/raw" || { \
	  echo "no data/builds/$(ACTIVE_BUILD)/raw; run \`python -m pipeline fetch\` first"; exit 1; }
	@(cd data && uv run python -m pipeline loot \
	  --build "$(ACTIVE_BUILD)" --engine "$(abspath $(ENGINE_DIR))")

.PHONY: loot-check
# loot-check is the offline gate on what `loot` wrote: the committed
# build's counts, and the curated overlays' shape and provenance. It
# needs no engine checkout and no raw/, which is why CI runs it in the
# data workflow's test job (as part of pytest) rather than regenerating
# -- the same split simdb.bin and gametables/ already have.
loot-check:
	@(cd data && uv run python -m pipeline phases --check)
	@(cd data && uv run pytest tests/test_loot_build.py tests/test_loot_overlay.py \
	  tests/test_loot_buffs.py tests/test_phases.py -q --no-cov)
