"""addon-data.json rendered as the Lua chunk the addon loads.

The file is committed so the addon is installable straight from a
checkout and so a release zip needs no build step. CI's drift gate
(`python -m pipeline addon-data --check`) is what keeps it honest.

The chunk sets `ns.Data` and returns it, which is the pattern every
module in `addon/ForeverSixty/` uses: in the game `...` is
`addonName, addonTable` so `ns` is the addon table; under busted's
`require`, the second value is the chunk's filepath (a string, not
nil), so `ns = ns or {}` would never allocate a table there. Instead
`ns = type(ns) == "table" and ns or {}` only keeps `ns` when it is
already a table and falls back to a fresh one otherwise, and the
return value is what the spec receives.
"""

from __future__ import annotations

from pathlib import Path

from pipeline.addonbis import SOURCE_KIND_CODES, AddonBisError
from pipeline.addondata import build_addon_data
from pipeline.models import AddonData

LUA_PATH = Path("../addon/ForeverSixty/Data.lua")

GENERATED = "-- Code generated by `python -m pipeline addon-data`. DO NOT EDIT."


def _quote(value: str) -> str:
    """A Lua short string literal. Backslash first, or the quote escape is re-escaped."""
    escaped = value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n")
    return f'"{escaped}"'


def _number(value: float) -> str:
    """A Lua number literal, integers without a trailing .0."""
    return str(int(value)) if float(value).is_integer() else repr(float(value))


def _class_lua(slug: str, tabs: list) -> str:
    lines = [f"\t\t[{_quote(slug)}] = {{", "\t\t\ttabs = {"]
    for tab in tabs:
        lines.append(f"\t\t\t\t{{ name = {_quote(tab.name)}, talents = {{")
        for talent in tab.talents:
            lines.append(
                f"\t\t\t\t\t{{ name = {_quote(talent.name)}, tier = {talent.tier}, "
                f"column = {talent.column}, maxRank = {talent.max_rank}, node = {talent.node} }},"
            )
        lines.append("\t\t\t\t} },")
    lines.append("\t\t\t},")
    lines.append("\t\t},")
    return "\n".join(lines)


def _rotations_lua(rotations: dict) -> list[str]:
    lines = ["\trotations = {"]
    for spec in sorted(rotations):
        lines.append(f"\t\t[{_quote(spec)}] = {{")
        for band in rotations[spec]:
            lines.append(f"\t\t\t{{ level = {band.level}, lines = {{")
            for line in band.lines:
                lines.append(
                    f"\t\t\t\t{{ spellId = {line.spell_id}, name = {_quote(line.name)}, "
                    f"condition = {_quote(line.condition)} }},"
                )
            lines.append("\t\t\t} },")
        lines.append("\t\t},")
    lines.append("\t},")
    return lines


def _source_kind_code(source_kind: str) -> str:
    code = SOURCE_KIND_CODES.get(source_kind)
    if code is None:
        raise AddonBisError(
            f"no Lua code for source_kind {source_kind!r}; add it to SOURCE_KIND_CODES"
        )
    return code


def _bis_lua(bis: dict) -> list[str]:
    """`bis[spec][band][faction][slot] = { itemId, sourceKindCode }` -- ids
    only (addonbis.py's own load-bearing decision) and positional rather
    than named fields, and faction/slot as bare Lua identifiers rather than
    quoted keys, because this table is the addition the lane brief's size
    budget is about: named fields alone would nearly double it across 27
    specs. Tooltip.lua's SOURCE_KIND_NAMES decodes the single-letter code
    back for advanced detail."""
    lines = ["\tbis = {"]
    for spec in sorted(bis):
        lines.append(f"\t\t[{_quote(spec)}] = {{")
        for band in bis[spec]:
            lines.append(f"\t\t\t[{band.level}] = {{")
            for faction in sorted(band.factions):
                lines.append(f"\t\t\t\t{faction} = {{")
                for slot in sorted(band.factions[faction]):
                    item = band.factions[faction][slot]
                    code = _source_kind_code(item.source_kind)
                    lines.append(f"\t\t\t\t\t{slot} = {{ {item.item_id}, {_quote(code)} }},")
                lines.append("\t\t\t\t},")
            lines.append("\t\t\t},")
        lines.append("\t\t},")
    lines.append("\t},")
    return lines


def _bis_new_lua(bis: dict) -> list[str]:
    """`bis_new[spec][band][faction] = { itemId, ... }` -- the item ids
    newly best at that band, for the tooltip's "(new at <band>)" tag."""
    lines = ["\tbis_new = {"]
    for spec in sorted(bis):
        lines.append(f"\t\t[{_quote(spec)}] = {{")
        for band in bis[spec]:
            lines.append(f"\t\t\t[{band.level}] = {{")
            for faction in sorted(band.new_at_band):
                ids = ", ".join(str(item_id) for item_id in band.new_at_band[faction])
                lines.append(f"\t\t\t\t{faction} = {{ {ids} }},")
            lines.append("\t\t\t},")
        lines.append("\t\t},")
    lines.append("\t},")
    return lines


def render_lua(data: AddonData) -> str:
    lines = [
        GENERATED,
        "-- Source: data/builds/<build>/addon-data.json",
        "local _, ns = ...",
        "ns = type(ns) == \"table\" and ns or {}",
        "",
        "ns.Data = {",
        f"\tbuild = {_quote(data.build)},",
        "\tclasses = {",
    ]
    for slug in sorted(data.classes):
        lines.append(_class_lua(slug, data.classes[slug].tabs))
    lines.append("\t},")
    lines.append("\tweights = {")
    for spec in sorted(data.weights):
        pairs = ", ".join(
            f"[{_quote(stat)}] = {_number(value)}"
            for stat, value in sorted(data.weights[spec].items())
        )
        lines.append(f"\t\t[{_quote(spec)}] = {{ {pairs} }},")
    lines.append("\t},")
    lines.extend(_rotations_lua(data.rotations))
    lines.extend(_bis_lua(data.bis))
    lines.extend(_bis_new_lua(data.bis))
    lines.append("}")
    lines.append("")
    lines.append("return ns.Data")
    return "\n".join(lines) + "\n"


def write_lua(
    build: str,
    root: Path = Path("builds"),
    curated_dir: Path = Path("curated"),
    lua_path: Path = LUA_PATH,
) -> Path:
    lua_path.parent.mkdir(parents=True, exist_ok=True)
    lua_path.write_text(
        render_lua(build_addon_data(build, root=root, curated_dir=curated_dir)), encoding="utf-8"
    )
    return lua_path


def lua_has_drifted(
    build: str,
    root: Path = Path("builds"),
    curated_dir: Path = Path("curated"),
    lua_path: Path = LUA_PATH,
) -> bool:
    wanted = render_lua(build_addon_data(build, root=root, curated_dir=curated_dir))
    return not lua_path.exists() or lua_path.read_text(encoding="utf-8") != wanted
