"""The canonical spec list, and the Go and TypeScript generated from it.

The interface contract is explicit: `data/curated/specs.json` is the list and
"nothing hardcodes a spec list elsewhere". The two generated files it names --
`sim/specs/specs.go` and `web/src/lib/sim/specs.ts` -- are consumed by the
engine, api and web lanes, so their shape is contract too.

`tree_index` is the tree `position` the pipeline writes into
`builds/<build>/talents/<class-slug>.json`. One spec name deliberately differs
from the client's tree name: the druid's "Feral Combat" tree is the Feral
spec, which is what design section 2.3 calls it.
"""

from __future__ import annotations

import json
from pathlib import Path

from pipeline.models import SpecRecord

ROLES = frozenset({"dps", "tank", "healer"})

GO_PATH = Path("../sim/specs/specs.go")
TS_PATH = Path("../web/src/lib/sim/specs.ts")

GENERATED = "// Code generated by `python -m pipeline specs`. DO NOT EDIT."


class SpecError(SystemExit):
    """curated/specs.json says something the pipeline will not publish."""


def load_specs(curated_dir: Path = Path("curated")) -> list[SpecRecord]:
    path = curated_dir / "specs.json"
    if not path.exists():
        raise SpecError(f"missing {path}")
    records: list[SpecRecord] = []
    seen: set[str] = set()
    for entry in json.loads(path.read_text(encoding="utf-8")):
        record = SpecRecord(**entry)
        if record.spec != f"{record.class_slug}-{record.spec_slug}":
            raise SpecError(
                f"spec key {record.spec!r} is not "
                f"{record.class_slug!r} + '-' + {record.spec_slug!r}"
            )
        if record.role not in ROLES:
            raise SpecError(
                f"spec {record.spec} has role {record.role!r}; use one of {sorted(ROLES)}"
            )
        if record.spec in seen:
            raise SpecError(f"specs.json names {record.spec} twice")
        seen.add(record.spec)
        records.append(record)
    return sorted(records, key=lambda record: (record.class_slug, record.tree_index))


def render_go(specs: list[SpecRecord]) -> str:
    rows = "\n".join(
        f'\t{{Spec: "{s.spec}", ClassSlug: "{s.class_slug}", SpecSlug: "{s.spec_slug}", '
        f'Name: "{s.name}", Role: "{s.role}", TreeIndex: {s.tree_index}}},'
        for s in specs
    )
    return f"""{GENERATED}
// Source: data/curated/specs.json

// Package specs is the canonical list of playable specialisations.
package specs

// Spec is one playable specialisation. Spec is the spec key the whole site
// keys on, for example "warrior-fury".
type Spec struct {{
\tSpec      string `json:"spec"`
\tClassSlug string `json:"class_slug"`
\tSpecSlug  string `json:"spec_slug"`
\tName      string `json:"name"`
\tRole      string `json:"role"`
\tTreeIndex int    `json:"tree_index"`
}}

// All is every spec, ordered by class slug then talent tree position.
var All = []Spec{{
{rows}
}}

// ByKey indexes All by its spec key.
var ByKey = func() map[string]Spec {{
\tindexed := make(map[string]Spec, len(All))
\tfor _, spec := range All {{
\t\tindexed[spec.Spec] = spec
\t}}
\treturn indexed
}}()
"""


def render_ts(specs: list[SpecRecord]) -> str:
    rows = "\n".join(
        f"  {{\n"
        f"    spec: '{s.spec}',\n"
        f"    class_slug: '{s.class_slug}',\n"
        f"    spec_slug: '{s.spec_slug}',\n"
        f"    name: '{s.name}',\n"
        f"    role: '{s.role}',\n"
        f"    tree_index: {s.tree_index},\n"
        f"  }},"
        for s in specs
    )
    return f"""{GENERATED}
// Source: data/curated/specs.json

export type SpecRole = 'dps' | 'tank' | 'healer';

export interface Spec {{
  spec: string;
  class_slug: string;
  spec_slug: string;
  name: string;
  role: SpecRole;
  tree_index: number;
}}

/** Every spec, ordered by class slug then talent tree position. */
export const SPECS: readonly Spec[] = [
{rows}
];

/** Every spec indexed by its spec key, for example 'warrior-fury'. */
export const SPEC_BY_KEY: Readonly<Record<string, Spec>> = Object.fromEntries(
  SPECS.map((spec) => [spec.spec, spec]),
);
"""


def _rendered(
    curated_dir: Path, go_path: Path, ts_path: Path
) -> tuple[tuple[Path, str], ...]:
    specs = load_specs(curated_dir)
    return ((go_path, render_go(specs)), (ts_path, render_ts(specs)))


def write_specs(
    curated_dir: Path = Path("curated"),
    go_path: Path = GO_PATH,
    ts_path: Path = TS_PATH,
) -> tuple[Path, Path]:
    for path, source in _rendered(curated_dir, go_path, ts_path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    return go_path, ts_path


def check_specs(
    curated_dir: Path = Path("curated"),
    go_path: Path = GO_PATH,
    ts_path: Path = TS_PATH,
) -> list[Path]:
    """The generated files that no longer match the curated list.

    `specs` is not a per-build emitter, so CI's build job never runs it; the
    drift gate is this, run in the test job and by tests/test_specs.py. It
    catches an edit to `curated/specs.json` that was never regenerated *and*
    an edit made straight to a generated file, which is why it compares
    contents rather than timestamps.
    """
    return [
        path
        for path, source in _rendered(curated_dir, go_path, ts_path)
        if not path.exists() or path.read_text(encoding="utf-8") != source
    ]
