"""The canonical spec list, and the Go and TypeScript generated from it.

The interface contract is explicit: `data/curated/specs.json` is the list and
"nothing hardcodes a spec list elsewhere". The two generated files it names --
`sim/specs/specs.go` and `web/src/lib/sim/specs.ts` -- are consumed by the
engine, api and web lanes, so their shape is contract too.

`tree_index` is the tree `position` the pipeline writes into
`builds/<build>/talents/<class-slug>.json`. One spec name deliberately differs
from the client's tree name: the druid's "Feral Combat" tree is the Feral
spec, which is what design section 2.3 calls it.
"""

from __future__ import annotations

import json
from pathlib import Path

from pipeline.models import SpecRecord
from pipeline.simdb.statmap import STAT_IDS

ROLES = frozenset({"dps", "tank", "healer"})

GO_PATH = Path("../sim/specs/specs.go")
TS_PATH = Path("../web/src/lib/sim/specs.ts")
# web/.prettierrc printWidth; the TypeScript renderer breaks lists the way prettier would.
TS_PRINT_WIDTH = 110

GENERATED = "// Code generated by `python -m pipeline specs`. DO NOT EDIT."


class SpecError(SystemExit):
    """curated/specs.json says something the pipeline will not publish."""


def load_specs(curated_dir: Path = Path("curated")) -> list[SpecRecord]:
    path = curated_dir / "specs.json"
    if not path.exists():
        raise SpecError(f"missing {path}")
    records: list[SpecRecord] = []
    seen: set[str] = set()
    for entry in json.loads(path.read_text(encoding="utf-8")):
        record = SpecRecord(**entry)
        if record.spec != f"{record.class_slug}-{record.spec_slug}":
            raise SpecError(
                f"spec key {record.spec!r} is not "
                f"{record.class_slug!r} + '-' + {record.spec_slug!r}"
            )
        if record.role not in ROLES:
            raise SpecError(
                f"spec {record.spec} has role {record.role!r}; use one of {sorted(ROLES)}"
            )
        if record.reference_stat not in STAT_IDS:
            raise SpecError(
                f"spec {record.spec} has reference_stat {record.reference_stat!r}; "
                f"contract 10.1 A7's vocabulary is the engine's Stat enum in snake "
                f"case -- use one of {sorted(STAT_IDS)}"
            )
        if not record.weight_stats:
            raise SpecError(f"spec {record.spec} has an empty weight_stats")
        unknown = [s for s in record.weight_stats if s not in STAT_IDS]
        if unknown:
            raise SpecError(
                f"spec {record.spec} has weight_stats {unknown!r}, not in the "
                f"engine's Stat enum -- use ids from {sorted(STAT_IDS)}"
            )
        if len(set(record.weight_stats)) != len(record.weight_stats):
            raise SpecError(f"spec {record.spec} lists a weight_stats entry twice")
        if record.reference_stat not in record.weight_stats:
            raise SpecError(
                f"spec {record.spec} has reference_stat {record.reference_stat!r}, "
                f"which is not in its own weight_stats {record.weight_stats!r}; "
                f"WeightsSpec.validate refuses a default request built this way"
            )
        if record.spec in seen:
            raise SpecError(f"specs.json names {record.spec} twice")
        seen.add(record.spec)
        records.append(record)
    return sorted(records, key=lambda record: (record.class_slug, record.tree_index))


def render_go(specs: list[SpecRecord]) -> str:
    def weight_stats_literal(stats: list[str]) -> str:
        quoted = ", ".join(f'"{stat}"' for stat in stats)
        return f"[]string{{{quoted}}}"

    rows = "\n".join(
        f'\t{{Spec: "{s.spec}", ClassSlug: "{s.class_slug}", SpecSlug: "{s.spec_slug}", '
        f'Name: "{s.name}", Role: "{s.role}", TreeIndex: {s.tree_index}, '
        f'ReferenceStat: "{s.reference_stat}", '
        f'WeightStats: {weight_stats_literal(s.weight_stats)}}},'
        for s in specs
    )
    return f"""{GENERATED}
// Source: data/curated/specs.json

// Package specs is the canonical list of playable specialisations.
package specs

// Spec is one playable specialisation. Spec is the spec key the whole site
// keys on, for example "warrior-fury".
type Spec struct {{
\tSpec          string `json:"spec"`
\tClassSlug     string `json:"class_slug"`
\tSpecSlug      string `json:"spec_slug"`
\tName          string `json:"name"`
\tRole          string `json:"role"`
\tTreeIndex     int    `json:"tree_index"`
\tReferenceStat string `json:"reference_stat"`
\t// WeightStats are the stats that actually move this spec's damage or
\t// healing - the closed list /sim/weights offers, so a physical spec
\t// is never asked about spirit and a caster never sees unexplained
\t// zeros for expertise. ReferenceStat is always one of them.
\tWeightStats []string `json:"weight_stats"`
}}

// All is every spec, ordered by class slug then talent tree position.
var All = []Spec{{
{rows}
}}

// ByKey indexes All by its spec key.
var ByKey = func() map[string]Spec {{
\tindexed := make(map[string]Spec, len(All))
\tfor _, spec := range All {{
\t\tindexed[spec.Spec] = spec
\t}}
\treturn indexed
}}()
"""


def render_ts(specs: list[SpecRecord]) -> str:
    def weight_stats_literal(stats: list[str]) -> str:
        # Prettier's rule, so a regenerated file is byte-identical to a
        # formatted one: the list stays on one line while the whole row fits
        # in printWidth, and breaks to one stat per line when it does not.
        inline = "[" + ", ".join(f"'{stat}'" for stat in stats) + "]"
        if len(f"    weight_stats: {inline},") <= TS_PRINT_WIDTH:
            return inline
        lines = "".join(f"      '{stat}',\n" for stat in stats)
        return f"[\n{lines}    ]"

    rows = "\n".join(
        f"  {{\n"
        f"    spec: '{s.spec}',\n"
        f"    class_slug: '{s.class_slug}',\n"
        f"    spec_slug: '{s.spec_slug}',\n"
        f"    name: '{s.name}',\n"
        f"    role: '{s.role}',\n"
        f"    tree_index: {s.tree_index},\n"
        f"    reference_stat: '{s.reference_stat}',\n"
        f"    weight_stats: {weight_stats_literal(s.weight_stats)},\n"
        f"  }},"
        for s in specs
    )
    return f"""{GENERATED}
// Source: data/curated/specs.json

export type SpecRole = 'dps' | 'tank' | 'healer';

export interface Spec {{
  spec: string;
  class_slug: string;
  spec_slug: string;
  name: string;
  role: SpecRole;
  tree_index: number;
  reference_stat: string;
  /** The closed list of stats /sim/weights offers; reference_stat is always one of them. */
  weight_stats: readonly string[];
}}

/** Every spec, ordered by class slug then talent tree position. */
export const SPECS: readonly Spec[] = [
{rows}
];

/** Every spec indexed by its spec key, for example 'warrior-fury'. */
export const SPEC_BY_KEY: Readonly<Record<string, Spec>> = Object.fromEntries(
  SPECS.map((spec) => [spec.spec, spec]),
);
"""


def _rendered(
    curated_dir: Path, go_path: Path, ts_path: Path
) -> tuple[tuple[Path, str], ...]:
    specs = load_specs(curated_dir)
    return ((go_path, render_go(specs)), (ts_path, render_ts(specs)))


def write_specs(
    curated_dir: Path = Path("curated"),
    go_path: Path = GO_PATH,
    ts_path: Path = TS_PATH,
) -> tuple[Path, Path]:
    for path, source in _rendered(curated_dir, go_path, ts_path):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(source, encoding="utf-8")
    return go_path, ts_path


def check_specs(
    curated_dir: Path = Path("curated"),
    go_path: Path = GO_PATH,
    ts_path: Path = TS_PATH,
) -> list[Path]:
    """The generated files that no longer match the curated list.

    `specs` is not a per-build emitter, so CI's build job never runs it; the
    drift gate is this, run in the test job and by tests/test_specs.py. It
    catches an edit to `curated/specs.json` that was never regenerated *and*
    an edit made straight to a generated file, which is why it compares
    contents rather than timestamps.
    """
    return [
        path
        for path, source in _rendered(curated_dir, go_path, ts_path)
        if not path.exists() or path.read_text(encoding="utf-8") != source
    ]
