// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import fixtureTalents from '../../fixtures/planner/talents/warrior.json';
import { indexTalents, type TalentIndex } from './rules';
import type { TalentFile } from './types';
import { createFakeEngine } from '../../fixtures/sim/engine-fake';
import { createBrokenWorker, createFakeWorker } from '../../test-support/fake-worker';
import { createPool, type PoolWorker } from '../sim/worker';
import type { SimCharacter } from '../sim/character';
import { LIVE_DEBOUNCE_MS, createLiveDps } from './live-dps.svelte';

const character: SimCharacter = {
  name: 'Thrallgar',
  spec: 'warrior-fury',
  class_slug: 'warrior',
  race_slug: 'orc',
  talent_level: 60,
  level: 60,
  tree_version: '1.15.9.69722',
  point_order: [2001, 2002],
  gear: { head: 12640 },
  gear_slots: [],
  professions: [],
  bags: [],
  bank: [],
  sets: [],
  loadouts: [],
  buffs: [],
  consumables: [],
  source: { kind: 'manual', ref: '', captured_at: '2026-09-14T10:00:00Z' },
};

/** The shared in-process worker (Task 3), wrapped so each test names its own tick rate. */
function fakeWorker(tickMs = 0): PoolWorker {
  return createFakeWorker(createFakeEngine({ tickMs, ticks: 3 }));
}

const live = () => createLiveDps({ pool: createPool({ hardwareConcurrency: 2, spawn: fakeWorker }) });

/**
 * The fixture warrior's talent index; the engine's talents string is built from it. Read
 * from `src/fixtures/planner/` directly -- the same checked-in fixture every other unit test
 * in this lane imports (store.test.ts, character.test.ts, fs1.test.ts) -- rather than from
 * `public/data/<build>/`, which is generated by `npm run sync` and pruned to whatever
 * `active-build.json` currently names; reading through that path would make this test's
 * pass/fail depend on when sync last ran and against which build.
 */
async function warriorIndex(): Promise<TalentIndex> {
  return indexTalents(fixtureTalents as TalentFile);
}

afterEach(() => vi.useRealTimers());

describe('createLiveDps', () => {
  it('is off until something is requested', () => {
    const dps = live();
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(0);
    dps.dispose();
  });

  it('debounces a burst of edits into one run', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    dps.request(character, index);
    dps.request(character, index);
    expect(dps.state).toBe('pending');
    await vi.advanceTimersByTimeAsync(LIVE_DEBOUNCE_MS - 1);
    expect(dps.state).toBe('pending');
    await vi.advanceTimersByTimeAsync(50);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('ready');
    expect(dps.estimate.mean).toBeGreaterThan(0);
    dps.dispose();
  });

  it('runs 500 iterations, which is what "under a second" buys', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    expect(dps.iterationsRun).toBe(500);
    dps.dispose();
  });

  it('keeps the last figure while the next one is computed', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    const first = dps.estimate.mean;
    dps.request({ ...character, gear: { head: 12641 } }, index);
    expect(dps.state).toBe('pending');
    expect(dps.estimate.mean).toBe(first);
    dps.dispose();
  });

  it('keeps the last figure when it is told to stop, and forgets it only when cleared', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    const first = dps.estimate.mean;
    expect(first).toBeGreaterThan(0);

    // A build that drops a point stops simming but still shows what it last measured.
    dps.request(null, null);
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(first);

    // A class change is a different question, not a stale answer.
    dps.clear();
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(0);
    dps.dispose();
  });

  it('goes off, not to an error, when there is no character to sim', async () => {
    const index = await warriorIndex();
    const dps = live();
    dps.request(null, index);
    expect(dps.state).toBe('off');
    dps.dispose();
  });

  it('asks a healer for its effective HPS, not its damage, and says the figure is HPS-sized', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request({ ...character, spec: 'priest-holy', class_slug: 'priest' }, index);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('ready');
    // The fake's healer draws around 380 effective HPS; its damage fixture is in the thousands.
    expect(dps.estimate.mean).toBeGreaterThan(300);
    expect(dps.estimate.mean).toBeLessThan(460);
    expect(dps.estimate.error).toBeGreaterThan(0);
    expect(dps.iterationsRun).toBe(500);
    dps.dispose();
  });

  it("asks a tank for its score, from the result's tank block", async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request({ ...character, spec: 'warrior-protection' }, index);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('ready');
    expect(dps.estimate.mean).toBeGreaterThan(20_000);
    expect(dps.estimate.mean).toBeLessThan(34_000);
    dps.dispose();
  });

  it('sends role_metrics for a healer and a tank and leaves a damage spec a plain run', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const seen: { spec: string; role_metrics?: boolean }[] = [];
    const engine = createFakeEngine({ tickMs: 0, ticks: 1 });
    const spy = {
      ...engine,
      simSplit: (json: string, n: number) => {
        seen.push(JSON.parse(json) as { spec: string; role_metrics?: boolean });
        return engine.simSplit(json, n);
      },
    };
    const dps = createLiveDps({
      pool: createPool({ hardwareConcurrency: 1, spawn: () => createFakeWorker(spy) }),
    });
    for (const spec of ['warrior-fury', 'priest-holy', 'warrior-protection']) {
      dps.request({ ...character, spec }, index);
      await vi.runAllTimersAsync();
    }
    expect(seen.map((request) => [request.spec, request.role_metrics])).toEqual([
      ['warrior-fury', undefined],
      ['priest-holy', true],
      ['warrior-protection', true],
    ]);
    dps.dispose();
  });

  it('is an error, not a damage number under an HPS label, when a healer comes back without its figure', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const engine = createFakeEngine({ tickMs: 0, ticks: 1 });
    const stripped = {
      ...engine,
      simCombine: (json: string) => {
        const { healing: _healing, ...rest } = JSON.parse(engine.simCombine(json)) as Record<string, unknown>;
        return JSON.stringify(rest);
      },
    };
    const dps = createLiveDps({
      pool: createPool({ hardwareConcurrency: 1, spawn: () => createFakeWorker(stripped) }),
    });
    dps.request({ ...character, spec: 'priest-holy', class_slug: 'priest' }, index);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('error');
    expect(dps.message).toBe('HPS estimate unavailable for this build.');
    dps.dispose();
  });

  it('says so rather than throwing when the engine fails', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = createLiveDps({
      pool: createPool({ hardwareConcurrency: 1, spawn: () => createBrokenWorker() }),
    });
    dps.request(character, index);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('error');
    expect(dps.message).not.toBeNull();
    dps.dispose();
  });
});
