// @vitest-environment jsdom
import { afterEach, describe, expect, it, vi } from 'vitest';
import fixtureTalents from '../../fixtures/planner/talents/warrior.json';
import { indexTalents, type TalentIndex } from './rules';
import type { TalentFile } from './types';
import { createFakeEngine } from '../../fixtures/sim/engine-fake';
import { createBrokenWorker, createFakeWorker } from '../../test-support/fake-worker';
import { createPool, type PoolWorker } from '../sim/worker';
import type { SimCharacter } from '../sim/character';
import { LIVE_DEBOUNCE_MS, createLiveDps } from './live-dps.svelte';

const character: SimCharacter = {
  name: 'Thrallgar',
  spec: 'warrior-fury',
  class_slug: 'warrior',
  race_slug: 'orc',
  talent_level: 60,
  tree_version: '1.15.9.69722',
  point_order: [2001, 2002],
  gear: { head: 12640 },
  gear_slots: [],
  professions: [],
  bags: [],
  bank: [],
  sets: [],
  loadouts: [],
  buffs: [],
  consumables: [],
  source: { kind: 'manual', ref: '', captured_at: '2026-09-14T10:00:00Z' },
};

/** The shared in-process worker (Task 3), wrapped so each test names its own tick rate. */
function fakeWorker(tickMs = 0): PoolWorker {
  return createFakeWorker(createFakeEngine({ tickMs, ticks: 3 }));
}

const live = () => createLiveDps({ pool: createPool({ hardwareConcurrency: 2, spawn: fakeWorker }) });

/**
 * The fixture warrior's talent index; the engine's talents string is built from it. Read
 * from `src/fixtures/planner/` directly -- the same checked-in fixture every other unit test
 * in this lane imports (store.test.ts, character.test.ts, fs1.test.ts) -- rather than from
 * `public/data/<build>/`, which is generated by `npm run sync` and pruned to whatever
 * `active-build.json` currently names; reading through that path would make this test's
 * pass/fail depend on when sync last ran and against which build.
 */
async function warriorIndex(): Promise<TalentIndex> {
  return indexTalents(fixtureTalents as TalentFile);
}

afterEach(() => vi.useRealTimers());

describe('createLiveDps', () => {
  it('is off until something is requested', () => {
    const dps = live();
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(0);
    dps.dispose();
  });

  it('debounces a burst of edits into one run', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    dps.request(character, index);
    dps.request(character, index);
    expect(dps.state).toBe('pending');
    await vi.advanceTimersByTimeAsync(LIVE_DEBOUNCE_MS - 1);
    expect(dps.state).toBe('pending');
    await vi.advanceTimersByTimeAsync(50);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('ready');
    expect(dps.estimate.mean).toBeGreaterThan(0);
    dps.dispose();
  });

  it('runs 500 iterations, which is what "under a second" buys', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    expect(dps.iterationsRun).toBe(500);
    dps.dispose();
  });

  it('keeps the last figure while the next one is computed', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    const first = dps.estimate.mean;
    dps.request({ ...character, gear: { head: 12641 } }, index);
    expect(dps.state).toBe('pending');
    expect(dps.estimate.mean).toBe(first);
    dps.dispose();
  });

  it('keeps the last figure when it is told to stop, and forgets it only when cleared', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = live();
    dps.request(character, index);
    await vi.runAllTimersAsync();
    const first = dps.estimate.mean;
    expect(first).toBeGreaterThan(0);

    // A build that drops a point stops simming but still shows what it last measured.
    dps.request(null, null);
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(first);

    // A class change is a different question, not a stale answer.
    dps.clear();
    expect(dps.state).toBe('off');
    expect(dps.estimate.mean).toBe(0);
    dps.dispose();
  });

  it('goes off, not to an error, when there is no character to sim', async () => {
    const index = await warriorIndex();
    const dps = live();
    dps.request(null, index);
    expect(dps.state).toBe('off');
    dps.dispose();
  });

  it('says so rather than throwing when the engine fails', async () => {
    const index = await warriorIndex();
    vi.useFakeTimers();
    const dps = createLiveDps({
      pool: createPool({ hardwareConcurrency: 1, spawn: () => createBrokenWorker() }),
    });
    dps.request(character, index);
    await vi.runAllTimersAsync();
    expect(dps.state).toBe('error');
    expect(dps.message).not.toBeNull();
    dps.dispose();
  });
});
