// Code generated by "make engine-pin". DO NOT EDIT.

package enginever

// Version is the short commit sha of wowsims-forever that sim.wasm, sim.js
// and the forever-sim binary were built from. It names the immutable wasm
// directory, the premium lane image tag, and every stored sim row.
const Version = "83f17d4b8"
