package enginever

import "testing"

// Version is the short commit sha of wowsims-forever the artifacts were
// built from. It is generated by `make engine-pin` from the root of the
// site repository and must never be edited by hand.
func TestVersionLooksLikeAShortSha(t *testing.T) {
	if len(Version) < 7 || len(Version) > 12 {
		t.Fatalf("Version = %q; want a 7-to-12 character short sha", Version)
	}
	for _, c := range Version {
		if !(c >= '0' && c <= '9' || c >= 'a' && c <= 'f') {
			t.Fatalf("Version = %q; want lowercase hexadecimal", Version)
		}
	}
}
