// web/scripts/ids-md.mjs
// sim/request/IDS.md is generated by the engine from its own protobuf descriptors and is
// the only place the buff, consumable and profession vocabulary exists. This parses it, so
// web/ holds the grouping and never a second copy of the list. A plain .mjs because
// scripts/sync-sim-ids.mjs runs under node long before any TypeScript is compiled;
// src/lib/sim/ids-md.test.ts drives it through vitest all the same.

/** @typedef {{ id: string, message: string }} BuffIdRow */
/** @typedef {{ id: string, sets: string }} ConsumableIdRow */
/** @typedef {{ buffs: BuffIdRow[], consumables: ConsumableIdRow[], professions: string[], worldBuffs: string[], stats: string[] }} SimIds */

/** A markdown table cell's contents, with the backticks IDS.md wraps every id in removed. */
function cell(text) {
  return text.trim().replace(/^`|`$/g, '');
}

/** True for `| --- | --- |` and for the header row, neither of which is data. */
function isStructural(cells) {
  return cells.every((value) => /^-{3,}$/.test(value)) || cells[0] === 'id' || cells[0] === 'slug';
}

/**
 * Every table row under each `## ` heading, keyed by the heading's lowercased text. Prose
 * is skipped by requiring a line to start and end with a pipe.
 * @param {string} markdown
 * @returns {Map<string, string[][]>}
 */
function sectionsOf(markdown) {
  /** @type {Map<string, string[][]>} */
  const sections = new Map();
  let heading = '';
  for (const line of markdown.split('\n')) {
    const title = /^##\s+(.+?)\s*$/.exec(line);
    if (title !== null) {
      heading = title[1].toLowerCase();
      if (!sections.has(heading)) sections.set(heading, []);
      continue;
    }
    const trimmed = line.trim();
    if (heading === '' || !trimmed.startsWith('|') || !trimmed.endsWith('|')) continue;
    const cells = trimmed.slice(1, -1).split('|').map(cell);
    if (isStructural(cells)) continue;
    sections.get(heading)?.push(cells);
  }
  return sections;
}

/**
 * @param {string} markdown
 * @returns {SimIds}
 */
export function parseIdsMarkdown(markdown) {
  const sections = sectionsOf(markdown);
  const buffRows = sections.get('buffs') ?? [];
  const consumableRows = sections.get('consumables') ?? [];
  const professionRows = sections.get('professions') ?? [];
  const worldRows = sections.get('world buffs') ?? [];
  // Contract A7 adds both of these sections; absent ones read as empty lists, so this
  // parser works against today's IDS.md and against the regenerated one unchanged.
  const statRows = sections.get('stats') ?? [];
  return {
    buffs: buffRows.map((cells) => ({ id: cells[0], message: cells[1] ?? '' })),
    consumables: consumableRows.map((cells) => ({ id: cells[0], sets: cells[1] ?? '' })),
    professions: professionRows.map((cells) => cells[0]),
    worldBuffs: worldRows.map((cells) => cells[0]),
    stats: statRows.map((cells) => cells[0]),
  };
}
