package main

import (
	"fmt"
	"sort"
	"strings"
	"time"

	"github.com/jhunthrop/foreversixty/sim/enginever"
)

// report renders one spec's search as markdown.
type report struct {
	opts     options
	in       inputs
	credits  map[int]credit
	eval     evaluation
	poolSize int
	elapsed  time.Duration
}

func (r report) markdown() string {
	var b strings.Builder
	t := r.in.setup.trees
	spec := r.in.setup.spec
	best := r.eval.Final[0]
	fmt.Fprintf(&b, "# Talent search: %s, level %d\n\n", spec.Name, r.opts.level)
	fmt.Fprintf(&b, "Generated by `sim/cmd/talent-search` against client %s, engine %s. Gear: the committed level-%d %s BiS set (%s), so only talents vary. ",
		r.in.clientBuild, enginever.Version, r.opts.level, r.opts.faction, r.in.setup.band.Race)
	fmt.Fprintf(&b, "%d candidates generated, %d screened at %d iterations, the best %d plus the guide re-simmed at %d iterations (seed %d, the same for every sim). Probes: %d iterations. Run time %s.\n\n",
		r.poolSize, len(r.eval.Screened)-1, r.opts.screenIters, len(r.eval.Final)-1, r.opts.finalIters, r.opts.seed, r.opts.probeIters, r.elapsed.Round(time.Second))
	r.writeVerdict(&b, best)
	r.writeCleanVerdict(&b)
	fmt.Fprintf(&b, "- Guide (frontmatter %s), re-read by talent id against %s: `%s`\n", r.in.guideCode, r.in.clientBuild, t.fs1(r.in.clientBuild, spec.ClassSlug, r.in.setup.band.Race, r.in.guide))
	if r.in.guideIssue != "" {
		fmt.Fprintf(&b, "- The guide is not a full legal build in %s: %s\n", r.in.clientBuild, r.in.guideIssue)
	}
	fmt.Fprintf(&b, "- Winner: `%s`\n", t.fs1(r.in.clientBuild, spec.ClassSlug, r.in.setup.band.Race, best.Build))
	if c, ok := r.bestClean(); ok && c.Label != r.eval.Guide.Label {
		fmt.Fprintf(&b, "- Winner keeping every unmodeled guide talent: `%s`\n", t.fs1(r.in.clientBuild, spec.ClassSlug, r.in.setup.band.Race, c.Build))
	}
	b.WriteString("\n")
	r.writeFinal(&b)
	r.writeEngineGaps(&b)
	r.writeCredits(&b)
	r.writeScreened(&b)
	return b.String()
}

func (r report) writeVerdict(b *strings.Builder, best result) {
	g := r.eval.Guide
	switch {
	case best.Label == g.Label:
		fmt.Fprintf(b, "**Verdict: the guide build is the best build found** (%.1f ± %.1f DPS).\n\n", g.DPS.Mean, g.DPS.Err)
	case best.Significant:
		fmt.Fprintf(b, "**Verdict: %s beats the guide by %+.1f DPS (%+.1f%%), beyond the combined error ±%.1f.** Guide %.1f ± %.1f, best %.1f ± %.1f.\n\n",
			best.Label, best.Delta, 100*best.Delta/g.DPS.Mean, best.DeltaErr, g.DPS.Mean, g.DPS.Err, best.DPS.Mean, best.DPS.Err)
	default:
		fmt.Fprintf(b, "**Verdict: no variant beats the guide beyond error.** Best: %s at %+.1f DPS (±%.1f combined). Guide %.1f ± %.1f.\n\n",
			best.Label, best.Delta, best.DeltaErr, g.DPS.Mean, g.DPS.Err)
	}
}

// removedUnmodeled is the talents b drops from the guide that the
// final classification calls unmodeled: their loss sims as free, so a
// gain that comes from moving them is the engine's blind spot, not a
// finding.
func removedUnmodeled(in inputs, credits map[int]credit, b build) []string {
	var out []string
	for _, id := range sortedIDs(in.guide) {
		if d := in.guide[id] - b[id]; d > 0 && classify(in.modeled[id], credits[id]) == classUnmodeled {
			out = append(out, fmt.Sprintf("%s (-%d)", in.setup.trees.byID[id].Name, d))
		}
	}
	return out
}

// writeCleanVerdict is the verdict restricted to finalists that drop
// no unmodeled guide talent - the claims the engine can actually back.
func (r report) writeCleanVerdict(b *strings.Builder) {
	if res, ok := r.bestClean(); ok {
		switch {
		case res.Label == r.eval.Guide.Label:
			b.WriteString("**Counting only variants that keep every unmodeled guide talent:** the guide is the best.\n\n")
		case res.Significant && res.Delta > 0:
			fmt.Fprintf(b, "**Counting only variants that keep every unmodeled guide talent:** %s, %+.1f DPS (±%.1f combined), beyond error.\n\n", res.Label, res.Delta, res.DeltaErr)
		default:
			fmt.Fprintf(b, "**Counting only variants that keep every unmodeled guide talent:** best is %s at %+.1f DPS (±%.1f combined), within error.\n\n", res.Label, res.Delta, res.DeltaErr)
		}
	}
}

// bestClean is the best finalist that drops no unmodeled guide talent
// (the guide itself qualifies, so there always is one).
func (r report) bestClean() (result, bool) {
	for _, res := range r.eval.Final {
		if len(removedUnmodeled(r.in, r.credits, res.Build)) == 0 {
			return res, true
		}
	}
	return result{}, false
}

func (r report) writeFinal(b *strings.Builder) {
	t := r.in.setup.trees
	b.WriteString("## Finalists\n\n")
	b.WriteString("| # | Build | Trees | DPS | ± | vs guide | Beyond error | Added | Removed | Drops unmodeled guide talents | Unmodeled talents in this build |\n")
	b.WriteString("|---|---|---|---|---|---|---|---|---|---|---|\n")
	for i, res := range r.eval.Final {
		added, removed := t.diffNames(r.in.guide, res.Build)
		fmt.Fprintf(b, "| %d | %s | %s | %.1f | %.1f | %+.1f ± %.1f | %s | %s | %s | %s | %s |\n",
			i+1, res.Label, t.summary(res.Build), res.DPS.Mean, res.DPS.Err, res.Delta, res.DeltaErr,
			yesNo(res.Significant), joinOrDash(added), joinOrDash(removed),
			joinOrDash(removedUnmodeled(r.in, r.credits, res.Build)), joinOrDash(r.unmodeledIn(res.Build)))
	}
	b.WriteString("\n")
}

func (r report) writeCredits(b *strings.Builder) {
	t := r.in.setup.trees
	b.WriteString("## What the engine credits each talent with\n\n")
	b.WriteString("Probed around the guide build: a talent the guide takes is removed, any other is added at max rank (legality ignored for the probe). Per-point DPS; *damage* means the probe moved DPS by more than 0.1% (every probe shares the base run's seed, so a talent the engine ignores reproduces it exactly). A talent the engine's code never reads is *unmodeled*: it sims as zero, and whatever it grants is either missing or given to every character regardless (the paladin engine registers Seal of Command unconditionally, for one).\n\n")
	b.WriteString("| Tree | Talent | Tier | Guide | Max | DPS/point | Probe diff ± err | Engine |\n|---|---|---|---|---|---|---|---|\n")
	for ti, tree := range t.trees {
		for _, n := range tree.Talents {
			c := r.credits[n.ID]
			fmt.Fprintf(b, "| %s | %s | %d | %d | %d | %+.2f | %+.1f ± %.1f | %s |\n",
				t.trees[ti].Name, n.Name, n.Tier, r.in.guide[n.ID], n.MaxRank, c.PerPoint, c.Diff, c.Err, r.engineStatus(n.ID, c))
		}
	}
	b.WriteString("\n")
}

func (r report) engineStatus(id int, c credit) string {
	return classify(r.in.modeled[id], c).String()
}

func (r report) writeScreened(b *strings.Builder) {
	t := r.in.setup.trees
	fmt.Fprintf(b, "## Every screened candidate (%d iterations)\n\n", r.opts.screenIters)
	b.WriteString("| Build | Trees | DPS | vs guide | Credit estimate |\n|---|---|---|---|---|\n")
	for _, res := range r.eval.Screened {
		fmt.Fprintf(b, "| %s | %s | %.1f | %+.1f ± %.1f | %+.1f |\n", res.Label, t.summary(res.Build), res.DPS.Mean, res.Delta, res.DeltaErr, res.Estimate)
	}
}

// unmodeledIn is the names of the talents b takes that the final
// classification calls unmodeled.
func (r report) unmodeledIn(b build) []string {
	t := r.in.setup.trees
	var out []string
	for _, id := range sortedIDs(b) {
		if classify(r.in.modeled[id], r.credits[id]) == classUnmodeled {
			out = append(out, fmt.Sprintf("%s (%d)", t.byID[id].Name, b[id]))
		}
	}
	sort.Strings(out)
	return out
}

// engineGaps is the final-classification-unmodeled talents worth the
// engine lane's attention: ones in the spec's own tree, or ones the
// guide itself takes, so a blind spot that actually matters to this
// spec does not get lost among every class's tier-1 utility picks.
func (r report) engineGaps() []string {
	t := r.in.setup.trees
	spec := r.in.setup.spec
	var out []string
	for ti, tree := range t.trees {
		for _, n := range tree.Talents {
			if classify(r.in.modeled[n.ID], r.credits[n.ID]) != classUnmodeled {
				continue
			}
			if ti != spec.TreeIndex && r.in.guide[n.ID] == 0 {
				continue
			}
			out = append(out, fmt.Sprintf("%s (%s, tier %d)", n.Name, tree.Name, n.Tier))
		}
	}
	return out
}

// writeEngineGaps lists the unmodeled talents the engine lane should
// actually look at: the spec's own tree, or anything the guide takes.
func (r report) writeEngineGaps(b *strings.Builder) {
	b.WriteString("## Engine gaps\n\n")
	gaps := r.engineGaps()
	if len(gaps) == 0 {
		b.WriteString("None: every talent the final classification calls unmodeled sits outside this spec's own tree, and the guide takes none of them.\n\n")
		return
	}
	b.WriteString("Talents the final classification calls unmodeled that sit in this spec's own tree or that the guide takes - what the engine lane is actually missing:\n\n")
	for _, g := range gaps {
		fmt.Fprintf(b, "- %s\n", g)
	}
	b.WriteString("\n")
}

func yesNo(v bool) string {
	if v {
		return "yes"
	}
	return "no"
}

func joinOrDash(s []string) string {
	if len(s) == 0 {
		return "-"
	}
	return strings.Join(s, ", ")
}
