local helper = require("spec_helper")
local mock = require("wow_mock")
local L = require("Locale")

describe("the keybind", function()
	it("Bindings.xml names the toggle binding under its own header", function()
		local file = assert(io.open("ForeverSixty/Bindings.xml", "r"))
		local xml = file:read("a")
		file:close()
		assert.is_truthy(xml:find('name="FOREVERSIXTY_TOGGLE"', 1, true))
		assert.is_truthy(xml:find('header="FOREVERSIXTY"', 1, true))
		assert.is_truthy(xml:find("FOREVERSIXTY_TOGGLE_WINDOW()", 1, true))
	end)

	describe("what Options.register wires up for it", function()
		local Options

		before_each(function()
			mock.install({ class = { name = "Paladin", token = "PALADIN" } })
			require("Theme").reset()
			helper.load("Prefs")
			helper.load("Widgets")
			helper.load("Export")
			helper.load("Gear")
			helper.load("Follow")
			helper.load("TalentGlow")
			helper.load("Tooltip")
			helper.load("ExportView")
			helper.load("FollowView")
			helper.load("GearView")
			helper.load("SettingsView")
			helper.load("Tracker")
			helper.load("Minimap")
			helper.load("Window")
			helper.load("Toast")
			Options = helper.load("Options")
			Options.data = { build = "1.60.1.69893", classes = {}, weights = {} }
		end)

		after_each(function()
			mock.uninstall()
		end)

		it("sets the header and name globals the XML file names", function()
			Options.register()
			assert.are.equal(L.bindingHeader, _G.BINDING_HEADER_FOREVERSIXTY)
			assert.are.equal(L.bindingToggle, _G.BINDING_NAME_FOREVERSIXTY_TOGGLE)
		end)

		it("toggles the window through the global the binding calls", function()
			Options.register()
			assert.is_false(require("Window").isOpen())
			_G.FOREVERSIXTY_TOGGLE_WINDOW()
			assert.is_true(require("Window").isOpen())
			_G.FOREVERSIXTY_TOGGLE_WINDOW()
			assert.is_false(require("Window").isOpen())
		end)

		it("leaves no binding globals behind for the next spec file", function()
			Options.register()
			mock.uninstall()
			assert.is_nil(_G.BINDING_HEADER_FOREVERSIXTY)
			assert.is_nil(_G.BINDING_NAME_FOREVERSIXTY_TOGGLE)
			assert.is_nil(_G.FOREVERSIXTY_TOGGLE_WINDOW)
		end)
	end)
end)
