"""The Droptimizer, Top Gear and settings-panel data for one build.

Parity contract section 6 as corrected by 10.4. Five outputs, one command:

    builds/<build>/loot.json        every source the two databases state
    builds/<build>/enchants.json    the enchants Top Gear's picker offers
    builds/<build>/suffixes.json    every random suffix and what it is worth
    builds/<build>/simbuffs.json    a name and icon per IDS.md id
    builds/<build>/items.json       gains `suffixes` and `faction_restriction`

Inputs, and why each is where it is:

* The engine fork's `assets/database/db.json`, at a path, because it moves
  with the engine pin and is not ours to vendor (see `pipeline/forkdb.py`).
* The build's own `zones.json`, `items.json` and `spells.json`, already
  committed. `items.json` is both an input (contract 10.4's build filter,
  and the buff panel's item names) and an output.
* The build's `raw/` CSVs. Like `simdb`, this command needs the downloaded
  DB2 exports and not just the normalized JSON: only `Map` says which zone
  is a raid, only `ItemSparse` says which item needs a PvP rank, and
  `SpellMisc` + `Item` + `ManifestInterfaceData` are where an icon comes
  from. Run `python -m pipeline fetch` first.
* `curated/loot/*.json` and `curated/simbuffs.json`.
* `../sim/request/IDS.md`, generated by the sim module from the engine's
  descriptors, which is the buff id list.

Run it after `normalize` and **before** `simdb`: it adds files to a
normalized build directory, refreshes the manifest to cover them, and
writes the two fork columns `pipeline/simdb/items.py` reads.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from pipeline.csvio import read_csv
from pipeline.forkdb import load_fork_database
from pipeline.loot.buffs import (
    IDS_MD,
    SIMBUFFS,
    build_simbuffs,
    client_tables,
    fork_tables,
    ids_md_ids,
    load_overrides,
)
from pipeline.loot.gear import (
    apply_fork_columns,
    build_enchants,
    build_suffixes,
    faction_restrictions,
    suffix_options,
)
from pipeline.loot.overlay import apply_overlays, load_overlays
from pipeline.loot.sources import build_loot, instance_types, pvp_ranks
from pipeline.manifest import refresh_manifest
from pipeline.normalize import write_document, write_records
from pipeline.normalize.sockets import check_no_sockets

logger = logging.getLogger(__name__)

LOOT = "loot.json"
ENCHANTS = "enchants.json"
SUFFIXES = "suffixes.json"


def _require(path: Path, command: str) -> None:
    if not path.exists():
        raise SystemExit(f"no {path}; run `python -m pipeline {command}` for this build first")


def write_loot_files(
    build: str,
    engine_dir: Path,
    root: Path = Path("builds"),
    overlay_dir: Path = Path("curated/loot"),
    curated_dir: Path = Path("curated"),
    ids_md: Path = IDS_MD,
) -> list[Path]:
    build_dir = root / build
    raw = build_dir / "raw"
    if not raw.exists():
        raise SystemExit(f"no raw data at {raw}; run `python -m pipeline fetch` first")
    for name in ("zones.json", "items.json", "spells.json"):
        _require(build_dir / name, "normalize")

    fork = load_fork_database(engine_dir)
    sparse_rows = read_csv(raw / "ItemSparse.csv")
    # The same guard normalize runs. A build reaching this command with a
    # socketed item would otherwise get a loot table for gear the rest of
    # the repository cannot model.
    check_no_sockets(sparse_rows, build)
    zone_rows = json.loads((build_dir / "zones.json").read_text(encoding="utf-8"))
    build_items = {
        int(row["id"])
        for row in json.loads((build_dir / "items.json").read_text(encoding="utf-8"))
    }

    # Contract 10.4's build filter happens inside build_loot, and its
    # pruning sweep with it -- so this runs BEFORE the overlay, which is
    # what lets a curated source with a deliberately empty item list (the
    # announced-but-unlooted Onyxia's Lair) survive.
    document, stats = build_loot(
        fork,
        {int(row["id"]): row["name"] for row in zone_rows},
        instance_types(read_csv(raw / "Map.csv"), zone_rows),
        pvp_ranks(sparse_rows),
        build_items,
    )
    document = apply_overlays(document, load_overlays(overlay_dir))

    enchants = build_enchants(fork)
    suffixes = build_suffixes(fork)
    client, icon_for = client_tables(build_dir, raw)
    simbuffs = build_simbuffs(
        ids_md_ids(ids_md.read_text(encoding="utf-8")),
        fork_tables(fork) + client,
        load_overrides(curated_dir),
        icon_for,
    )
    write_document(document, build_dir / LOOT)
    write_records(enchants, build_dir / ENCHANTS)
    write_records(suffixes, build_dir / SUFFIXES)
    write_document(simbuffs, build_dir / SIMBUFFS)
    with_suffixes, restricted = apply_fork_columns(
        build_dir, suffix_options(fork), faction_restrictions(fork)
    )

    logger.info(
        "loot: %d sources naming %d items; %d fork ids left out because this build "
        "has no such item, %d fork source entries with no kind dropped; "
        "%d enchants, %d suffixes, %d buff ids; "
        "items.json: %d with suffix options, %d faction-restricted",
        len(document.sources),
        stats.items,
        stats.absent_items,
        stats.dropped_entries,
        len(enchants),
        len(suffixes),
        len(simbuffs.entries),
        with_suffixes,
        restricted,
    )
    refresh_manifest(build_dir)
    return [
        build_dir / LOOT,
        build_dir / ENCHANTS,
        build_dir / SUFFIXES,
        build_dir / SIMBUFFS,
        build_dir / "items.json",
    ]
