"""The Droptimizer, Top Gear and settings-panel data for one build.

Parity contract section 6 as corrected by 10.4. Five outputs, one command:

    builds/<build>/loot.json        every source the two databases state
    builds/<build>/enchants.json    the enchants Top Gear's picker offers
    builds/<build>/suffixes.json    every random suffix and what it is worth
    builds/<build>/simbuffs.json    a name and icon per IDS.md id
    builds/<build>/items.json       gains `suffixes` and `faction_restriction`
    builds/<build>/items/*.json     weapon rows the fork itemises get its own
                                     damage_min/damage_max/speed/dps, winning
                                     over `normalize`'s curve-derived value

Inputs, and why each is where it is:

* The engine fork's `assets/database/db.json`, at a path, because it moves
  with the engine pin and is not ours to vendor (see `pipeline/forkdb.py`).
* The build's own `zones.json`, `items.json` and `spells.json`, already
  committed. `items.json` is both an input (contract 10.4's build filter,
  and the buff panel's item names) and an output.
* The build's `raw/` CSVs. Like `simdb`, this command needs the downloaded
  DB2 exports and not just the normalized JSON: only `Map` says which zone
  is a raid, only `ItemSparse` says which item needs a PvP rank, and
  `SpellMisc` + `Item` + `ManifestInterfaceData` are where an icon comes
  from. Run `python -m pipeline fetch` first.
* `curated/loot/*.json` and `curated/simbuffs.json`.
* `../sim/request/IDS.md`, generated by the sim module from the engine's
  descriptors, which is the buff id list.

Run it after `normalize` and **before** `simdb`: it adds files to a
normalized build directory, refreshes the manifest to cover them, and
writes the two fork columns `pipeline/simdb/items.py` reads.
"""

from __future__ import annotations

import json
import logging
from pathlib import Path

from pipeline.classic_sources import load_classic_sources
from pipeline.csvio import read_csv
from pipeline.forkdb import load_fork_database
from pipeline.item_sources import load_item_sources
from pipeline.loot.buffs import (
    IDS_MD,
    SIMBUFFS,
    build_simbuffs,
    client_tables,
    fork_tables,
    ids_md_ids,
    load_overrides,
)
from pipeline.loot.gear import (
    apply_fork_columns,
    build_enchants,
    build_suffixes,
    faction_restrictions,
    suffix_options,
)
from pipeline.loot.overlay import apply_overlays, load_overlays
from pipeline.loot.pvp_faction import split_pvp_sources_by_faction
from pipeline.loot.reitemise import apply_reitemisation
from pipeline.loot.sources import apply_quest_opens_gate, build_loot, instance_types, pvp_ranks
from pipeline.loot.weapons import apply_fork_weapon_damage, fork_weapon_damage
from pipeline.manifest import refresh_manifest
from pipeline.normalize import write_document, write_records
from pipeline.normalize.sockets import check_no_sockets
from pipeline.quest_levels import load_quest_levels

logger = logging.getLogger(__name__)

LOOT = "loot.json"
ENCHANTS = "enchants.json"
SUFFIXES = "suffixes.json"


def _require(path: Path, command: str) -> None:
    if not path.exists():
        raise SystemExit(f"no {path}; run `python -m pipeline {command}` for this build first")


def write_loot_files(
    build: str,
    engine_dir: Path,
    root: Path = Path("builds"),
    overlay_dir: Path = Path("curated/loot"),
    curated_dir: Path = Path("curated"),
    ids_md: Path = IDS_MD,
    *,
    allow_shrink: bool = False,
) -> list[Path]:
    build_dir = root / build
    raw = build_dir / "raw"
    if not raw.exists():
        raise SystemExit(f"no raw data at {raw}; run `python -m pipeline fetch` first")
    for name in ("zones.json", "items.json", "spells.json"):
        _require(build_dir / name, "normalize")
    # `check_item_sparse_completeness` (pipeline/csvio.py) now guards the item
    # catalog itself -- comparing a NEW items.json against the build's last
    # committed one -- which is entirely `normalize`'s write, not this
    # command's (normalize-levels lane, 2026-09-29). The `_require` above
    # already refuses to run without a committed items.json, so whatever
    # normalize most recently wrote already passed that gate; there is
    # nothing of the same shape left for `loot` to check on its own raw
    # ItemSparse.csv read below. `allow_shrink` is kept on the signature and
    # CLI for a caller scripting both commands with one flag; it does
    # nothing here now.
    sparse_rows = read_csv(raw / "ItemSparse.csv")

    fork = load_fork_database(engine_dir)
    # The same guard normalize runs. A build reaching this command with a
    # socketed item would otherwise get a loot table for gear the rest of
    # the repository cannot model.
    check_no_sockets(sparse_rows, build)
    zone_rows = json.loads((build_dir / "zones.json").read_text(encoding="utf-8"))
    item_rows = json.loads((build_dir / "items.json").read_text(encoding="utf-8"))
    build_items = {int(row["id"]) for row in item_rows}
    item_inventory_types = {int(row["id"]): int(row["inventory_type"]) for row in item_rows}
    # wowhead-world-drops lane, 2026-09-29: `pipeline.loot.wowhead.
    # wowhead_additions`' own world-drop level-range fallback, for when
    # wowhead's own `dropped-by` rows state no per-creature level at all.
    item_required_levels = {
        int(row["id"]): int(row.get("required_level") or 0) for row in item_rows
    }

    # Quest levels come from the committed, merged quest-levels.json
    # (never fetched here): `loot` builds the site's committed data and
    # must run offline in CI the same way `simdb`/`normalize` do -- run
    # `python -m pipeline fetch-classic-quest-levels` once and
    # `python -m pipeline quest-levels` (the nightly step) to (re)write
    # it. A quest id absent from it (neither classic-db nor wowhead
    # covers it) falls back to the item-level proxy inside
    # build_loot/_keyed_sources.
    quest_levels = load_quest_levels(build_dir)

    # night-item-sources lane, 2026-09-28: the committed wowhead scrape
    # for items the fork database itself names no source for at all
    # (pipeline.item_sources' own doc). Same offline-in-CI contract as
    # quest_levels above -- `loot` reads the committed cache and never
    # touches the network; `python -m pipeline item-sources` is the only
    # step allowed to.
    item_sources = load_item_sources(build_dir)

    # src-classicdb lane, 2026-09-29: the committed cmangos/classic-db
    # dump parse (pipeline.classic_sources' own doc) -- same offline-in-CI
    # contract as quest_levels/item_sources above. Fills a gap between the
    # two: applied after the fork's own sources, before wowhead's.
    classic_sources = load_classic_sources(build_dir)

    # Contract 10.4's build filter happens inside build_loot, and its
    # pruning sweep with it -- so this runs BEFORE the overlay, which is
    # what lets a curated source with a deliberately empty item list (the
    # announced-but-unlooted Onyxia's Lair) survive.
    document, stats = build_loot(
        fork,
        {int(row["id"]): row["name"] for row in zone_rows},
        instance_types(read_csv(raw / "Map.csv"), zone_rows),
        pvp_ranks(sparse_rows),
        build_items,
        item_inventory_types,
        quest_levels,
        item_sources,
        classic_sources,
        zone_rows,
        item_required_levels,
    )
    # pvp-faction lane, 2026-09-29: splits every `pvp` source into its
    # alliance/horde copies (pipeline.loot.pvp_faction's own doc). Runs
    # BEFORE apply_reitemisation, same reasoning as that step's own
    # ordering below: a re-itemised item copied onto a classic twin's
    # source must land in the twin's ALREADY-split bucket, not a still-
    # mixed one.
    document, pvp_faction_stats = split_pvp_sources_by_faction(
        document, {int(row["id"]): row["name"] for row in item_rows}, classic_sources, zone_rows
    )
    # src-classicdb lane item 3: a Forever-new item sharing its name and
    # slot with a Classic item, still unsourced after fork+classic-db+
    # wowhead, inherits the classic item's own sources. Runs AFTER
    # build_loot (needs its finished sources to know what is still
    # unsourced) and BEFORE the overlay (a curated fact should be able to
    # override an inherited one same as any other).
    document, reitemised = apply_reitemisation(document, item_rows)
    document = apply_overlays(document, load_overlays(overlay_dir))
    # Quest-gates lane, 2026-09-29: AFTER the overlay, which is what
    # actually sets a raid's own LootSource.opens
    # (curated/loot/forever-raid-phases.json) -- see apply_quest_opens_
    # gate's own doc for why any earlier placement finds nothing to gate
    # a quest's turn-in item on.
    document = apply_quest_opens_gate(document, classic_sources)

    enchants = build_enchants(fork)
    suffixes = build_suffixes(fork)
    client, icon_for = client_tables(build_dir, raw)
    simbuffs = build_simbuffs(
        ids_md_ids(ids_md.read_text(encoding="utf-8")),
        fork_tables(fork) + client,
        load_overrides(curated_dir),
        icon_for,
    )
    write_document(document, build_dir / LOOT)
    write_records(enchants, build_dir / ENCHANTS)
    write_records(suffixes, build_dir / SUFFIXES)
    write_document(simbuffs, build_dir / SIMBUFFS)
    with_suffixes, restricted = apply_fork_columns(
        build_dir, suffix_options(fork), faction_restrictions(fork)
    )
    weapons_won = apply_fork_weapon_damage(build_dir, fork_weapon_damage(fork))

    logger.info(
        "loot: %d sources naming %d items (%d from classic-db's dump parse, %d from "
        "wowhead's item-sources.json scrape, %d from re-itemisation inheritance, "
        "%d quests with faction detail); "
        "pvp faction split: %d items via classic-db vendor, %d via title, %d unresolved "
        "and dropped; "
        "%d fork ids left out because this build has no such item, "
        "%d fork source entries with no kind dropped, %d zone sources with "
        "a zone id zones[] does not name, %d bosses dropped for having no name in "
        "either database; "
        "%d enchants, %d suffixes, %d buff ids; "
        "items.json: %d with suffix options, %d faction-restricted; "
        "items/*.json: %d weapon rows won by the fork's own damage",
        len(document.sources),
        stats.items,
        stats.classicdb_items,
        stats.wowhead_items,
        reitemised,
        len(document.quests),
        pvp_faction_stats.resolved_vendor,
        pvp_faction_stats.resolved_title,
        len(pvp_faction_stats.unresolved),
        stats.absent_items,
        stats.dropped_entries,
        stats.unnamed_zones,
        stats.dropped_unnamed_bosses,
        len(enchants),
        len(suffixes),
        len(simbuffs.entries),
        with_suffixes,
        restricted,
        weapons_won,
    )
    refresh_manifest(build_dir)
    return [
        build_dir / LOOT,
        build_dir / ENCHANTS,
        build_dir / SUFFIXES,
        build_dir / SIMBUFFS,
        build_dir / "items.json",
        *sorted((build_dir / "items").glob("*.json")),
    ]


def _load_committed_loot(build_dir: Path) -> dict:
    path = build_dir / LOOT
    if not path.exists():
        return {"sources": []}
    return json.loads(path.read_text(encoding="utf-8"))


def types_from_committed_loot(build_dir: Path) -> dict[int, int]:
    """zone id -> a `Map.InstanceType`-equivalent code (1 dungeon, 2
    raid), recovered from the CURRENTLY COMMITTED `loot.json`'s own
    dungeon/raid sources -- `merge_loot_files`' raw-free substitute for
    `instance_types()` (which needs `raw/Map.csv`, unavailable when the
    build's `raw/` was never fetched at all: night-fetch-guard,
    2026-09-29, wago.tools' ItemSparse export for this build is
    truncated and `check_item_sparse_completeness` refuses it).

    Degrades gracefully, not silently: a dungeon/raid zone that
    currently has ZERO sourced items would be invisible to this recovery
    (there is no committed source to read it off), but the fork's own
    database has not changed between a full run and a merge-only one, so
    every zone a full run would have found stays found here too, as
    long as at least one of its items already made it into the last full
    `loot.json`.
    """
    kind_code = {"dungeon": 1, "raid": 2}
    types: dict[int, int] = {}
    for source in _load_committed_loot(build_dir).get("sources", []):
        code = kind_code.get(source.get("kind", ""))
        zone_id = source.get("zone_id")
        if code and zone_id:
            types[int(zone_id)] = code
    return types


def pvp_ranks_from_committed_loot(build_dir: Path) -> dict[int, int]:
    """item id -> PvP rank, recovered from the currently committed
    `loot.json`'s own `pvp:rank-N` sources -- the raw-free substitute for
    `pvp_ranks()` (needs `raw/ItemSparse.csv`'s `RequiredPVPRank`,
    unavailable in merge-only mode, same reason as
    `types_from_committed_loot` above)."""
    ranks: dict[int, int] = {}
    for source in _load_committed_loot(build_dir).get("sources", []):
        if source.get("kind") == "pvp" and source.get("rank"):
            for item_id in source.get("items") or []:
                ranks[int(item_id)] = int(source["rank"])
    return ranks


def merge_loot_files(
    build: str,
    engine_dir: Path,
    root: Path = Path("builds"),
    overlay_dir: Path = Path("curated/loot"),
) -> list[Path]:
    """`python -m pipeline loot-merge`: re-derives `loot.json` ALONE from
    inputs already committed -- the engine fork checkout, and the
    build's own `zones.json`/`items.json` plus its `raw/quests/
    quest-levels.json`, `raw/items/item-sources.json` and `raw/classicdb/
    sources.json` caches -- WITHOUT `raw/ItemSparse.csv` or `raw/Map.csv`
    (see `write_loot_files`'s own doc: those need a real `fetch` run,
    which this build cannot do right now -- night-fetch-guard,
    2026-09-29).

    Two things `write_loot_files` reads off `raw/ItemSparse.csv` are
    therefore unavailable and handled by NOT reading them fresh: the
    dungeon/raid zone map (`types_from_committed_loot`, above) and PvP
    ranks (`pvp_ranks_from_committed_loot`, above) are recovered from
    the currently committed `loot.json` instead of raw CSVs, so a
    `loot-merge` run does not regress either away. `check_no_sockets`
    (an ItemSparse-only validation with no data of its own) and
    `check_item_sparse_completeness` are skipped outright, loudly logged
    -- there is nothing for either to validate without the CSV.

    Unlike `write_loot_files`, this writes ONLY `loot.json` -- enchants,
    suffixes, simbuffs and the fork weapon-damage/suffix-option columns
    on `items.json`/`items/*.json` all need the same engine pass
    `write_loot_files` already did last time they changed (the fork's
    own database, not `raw/`), so a merge-only run leaves them alone.
    """
    build_dir = root / build
    for name in ("zones.json", "items.json"):
        _require(build_dir / name, "normalize")
    logger.warning(
        "loot-merge: no raw/ItemSparse.csv or raw/Map.csv for %s -- the dungeon/raid zone "
        "map and PvP ranks are recovered from the currently committed loot.json instead of "
        "fetched fresh, and check_no_sockets/check_item_sparse_completeness are skipped "
        "(nothing to validate without the CSV)",
        build,
    )
    fork = load_fork_database(engine_dir)
    zone_rows = json.loads((build_dir / "zones.json").read_text(encoding="utf-8"))
    item_rows = json.loads((build_dir / "items.json").read_text(encoding="utf-8"))
    build_items = {int(row["id"]) for row in item_rows}
    item_inventory_types = {int(row["id"]): int(row["inventory_type"]) for row in item_rows}
    item_required_levels = {
        int(row["id"]): int(row.get("required_level") or 0) for row in item_rows
    }
    quest_levels = load_quest_levels(build_dir)
    item_sources = load_item_sources(build_dir)
    classic_sources = load_classic_sources(build_dir)

    document, stats = build_loot(
        fork,
        {int(row["id"]): row["name"] for row in zone_rows},
        types_from_committed_loot(build_dir),
        pvp_ranks_from_committed_loot(build_dir),
        build_items,
        item_inventory_types,
        quest_levels,
        item_sources,
        classic_sources,
        zone_rows,
        item_required_levels,
    )
    document, pvp_faction_stats = split_pvp_sources_by_faction(
        document, {int(row["id"]): row["name"] for row in item_rows}, classic_sources, zone_rows
    )
    document, reitemised = apply_reitemisation(document, item_rows)
    document = apply_overlays(document, load_overlays(overlay_dir))
    document = apply_quest_opens_gate(document, classic_sources)
    write_document(document, build_dir / LOOT)
    logger.info(
        "loot-merge: %d sources naming %d items (%d from classic-db, %d from wowhead, %d "
        "from re-itemisation inheritance); pvp faction split: %d via classic-db vendor, "
        "%d via title, %d unresolved and dropped; %d fork ids left out, %d fork entries "
        "with no kind dropped, %d bosses dropped for having no name in either database",
        len(document.sources),
        stats.items,
        stats.classicdb_items,
        stats.wowhead_items,
        reitemised,
        pvp_faction_stats.resolved_vendor,
        pvp_faction_stats.resolved_title,
        len(pvp_faction_stats.unresolved),
        stats.absent_items,
        stats.dropped_entries,
        stats.dropped_unnamed_bosses,
    )
    refresh_manifest(build_dir)
    return [build_dir / LOOT]
