"""`simbuffs.json`: what to call every id a sim request may name.

Parity contract 10.4, for design section 4.3's full buff panel. An id in
`sim/request/IDS.md` is a protobuf field or enum-value name, not a spell
id, so nothing downstream can render it: this file is the display name
and icon per id, resolved once at build time.

IDS.md is generated by the sim module from the engine's own descriptors,
so it is parsed here rather than restated -- an id the engine adds shows
up as a build that needs a name, not as a panel row nobody notices is
missing.

The join is by normalised name, with the two spellings IDS.md itself
documents (the id, and the id without its leading enum-name token) and
the singular of each for the engine's plural fields. 151 of the 165 ids
resolve that way on the pinned engine and build; the other 14 are
`data/curated/simbuffs.json`. An id that resolves through neither is a
hard error: a row with a blank name and `icons/.webp` is worse than a
build that refuses to emit.
"""

from __future__ import annotations

import json
import re
from collections.abc import Callable
from pathlib import Path

from pipeline.csvio import read_csv
from pipeline.curated import parse_sources
from pipeline.forkdb import ForkDatabase
from pipeline.icons import icon_names, resolve_icon
from pipeline.models import BuffOverride, SimBuffEntry, SimBuffsFile

SIMBUFFS = "simbuffs.json"
IDS_MD = Path("../sim/request/IDS.md")

#: Normalised name -> (display name, icon).
type NameTable = dict[str, tuple[str, str]]

_ROW = re.compile(r"^\| `([a-z0-9_]+)` \|", re.M)
#: The IDS.md sections whose ids this file covers. "Professions" is
#: deliberately absent: those are character slugs, not buffs.
_SECTIONS = ("## Buffs", "## Consumables")


class BuffError(SystemExit):
    """An IDS.md id has no name the build can show."""


def normalise(name: str) -> str:
    """A display name as an id-shaped key: lowercase, apostrophes gone."""
    return re.sub(r"[^a-z0-9]+", "_", name.lower().replace("'", "")).strip("_")


def ids_md_ids(text: str) -> list[str]:
    """Every buff and consumable id IDS.md lists, sorted and deduplicated.

    Three ids (`scroll_of_agility`, `scroll_of_protection`,
    `scroll_of_strength`) are in both tables, which is why this is a set
    and not a concatenation. A missing section is an error rather than an
    empty answer: IDS.md is generated, and a shape change there must not
    silently empty the buff panel.
    """
    found: set[str] = set()
    for marker in _SECTIONS:
        if marker not in text:
            raise BuffError(f"{marker!r} is not in IDS.md; its shape changed")
        section = text.split(marker, 1)[1].split("\n## ", 1)[0]
        found |= set(_ROW.findall(section))
    return sorted(found)


def _candidates(buff_id: str) -> list[str]:
    """The spellings a display name may take for this id, best first."""
    out: list[str] = []
    for base in (buff_id, buff_id[:-1] if buff_id.endswith("s") else None):
        if base is None:
            continue
        out.append(base)
        if "_" in base:
            out.append(base.split("_", 1)[1])
    return out


def fork_tables(fork: ForkDatabase) -> list[NameTable]:
    """The fork's own icon tables: name and icon in one row, so no client
    lookup is needed for the 97 ids they cover."""
    return [_table_from(fork.spell_icon_rows), _table_from(fork.item_icon_rows)]


def _table_from(rows: tuple[dict, ...]) -> NameTable:
    table: NameTable = {}
    for row in rows:
        if row.get("name") and row.get("icon"):
            table.setdefault(normalise(row["name"]), (row["name"], row["icon"]))
    return table


#: (item_id, spell_id) -> the icon the build ships for whichever is set.
type IconFor = Callable[[int, int], str]


def client_tables(build_dir: Path, raw: Path) -> tuple[list[NameTable], IconFor]:
    """The build's own spell and item names, with icons resolved through
    `ManifestInterfaceData` exactly as every other icon here is.

    Returns the two tables and the resolver, because a curated override
    names a client row rather than an icon and needs the same lookup.
    """
    names = icon_names(read_csv(raw / "ManifestInterfaceData.csv"))
    spell_icon = {
        int(row["SpellID"]): int(row["SpellIconFileDataID"] or 0)
        for row in read_csv(raw / "SpellMisc.csv")
        if row.get("SpellID")
    }
    item_icon = {
        int(row["ID"]): int(row["IconFileDataID"] or 0)
        for row in read_csv(raw / "Item.csv")
    }

    def table(path: Path, icons: dict[int, int], what: str) -> NameTable:
        built: NameTable = {}
        for row in json.loads(path.read_text(encoding="utf-8")):
            key = normalise(row["name"])
            if key in built:
                continue
            icon = resolve_icon(
                icons.get(int(row["id"]), 0), names, f"{what} {row['id']} ({row['name']})"
            )
            built[key] = (row["name"], icon)
        return built

    def icon_for(item_id: int, spell_id: int) -> str:
        if item_id:
            return resolve_icon(item_icon.get(item_id, 0), names, f"item {item_id}")
        return resolve_icon(spell_icon.get(spell_id, 0), names, f"spell {spell_id}")

    return (
        [
            table(build_dir / "spells.json", spell_icon, "spell"),
            table(build_dir / "items.json", item_icon, "item"),
        ],
        icon_for,
    )


def load_overrides(
    curated_dir: Path = Path("curated"), name: str = SIMBUFFS
) -> dict[str, BuffOverride]:
    """The curated ids, validated. A missing file is no overrides, which
    is a legal state only while every id happens to join."""
    path = curated_dir / name
    if not path.exists():
        return {}
    document = json.loads(path.read_text(encoding="utf-8"))
    parse_sources(document.get("sources", []), str(path))
    if not document.get("notes", "").strip():
        raise BuffError(f"{path} has no notes; say why each id needs a hand")
    overrides: dict[str, BuffOverride] = {}
    for key, value in document["entries"].items():
        override = BuffOverride(**value)
        if bool(override.item_id) == bool(override.spell_id):
            raise BuffError(
                f"{path} entry {key!r} must name exactly one of item_id or spell_id, "
                f"so its icon comes from the build rather than from this file"
            )
        overrides[key] = override
    return overrides


def build_simbuffs(
    ids: list[str],
    tables: list[NameTable],
    overrides: dict[str, BuffOverride],
    icon_for: IconFor,
) -> SimBuffsFile:
    entries: dict[str, SimBuffEntry] = {}
    unresolved: list[str] = []
    for buff_id in ids:
        override = overrides.get(buff_id)
        if override is not None:
            entries[buff_id] = SimBuffEntry(
                name=override.name,
                icon=icon_for(override.item_id, override.spell_id),
            )
            continue
        found = None
        for candidate in _candidates(buff_id):
            for table in tables:
                if candidate in table:
                    found = table[candidate]
                    break
            if found is not None:
                break
        if found is None:
            unresolved.append(buff_id)
            continue
        entries[buff_id] = SimBuffEntry(name=found[0], icon=found[1])
    if unresolved:
        raise BuffError(
            f"{len(unresolved)} IDS.md id(s) have no name in the fork database or "
            f"this build: {', '.join(unresolved)}. Add each to "
            f"data/curated/simbuffs.json with a source, or fix the join."
        )
    return SimBuffsFile(entries=dict(sorted(entries.items())))
