<!-- web/src/components/character/FactionCrest.svelte -->
<!-- design/specs/2026-10-04-guild-page.md §12.2: the guild header's identity-row mark,
     beside the h1 -- the flat faction logo (`factionLogoSrc`, FactionMark.astro's own
     second provenance note), inside ClassCrest.astro's own ring recipe (circular crop,
     ~16% inner padding, 2px box-shadow ring in the subject's own colour, --color-raised
     background fallback) ported to Svelte the same way ClassCrestRing.svelte already ports
     that recipe for a non-Astro caller (Vite's Astro integration only compiles `.astro`
     files reached from another `.astro` entry point).

     Owner's final build decision: the flat logo is the ONE emblem anywhere in this header
     -- this ring AND the band's watermark both read `factionLogoSrc`; FactionMark.astro's
     own 72px unit-frame shield/disc (`factionMarkSrc`) stays exactly as it is everywhere
     else on the site (nav chip, row descriptors, ClassHeader's faction toggle) -- this is
     a new, single-purpose component, never a `FactionMark.astro` edit (ruling 12.2.A: that
     component's own contract, "no ring, no background," is depended on by nine existing
     callers).

     Tailwind utility classes, not a scoped <style> block (found during this round's own
     build): this component's only output is conditional on `faction`, which is unknown at
     Astro's one-time SSR pass for the GuildShell island (the header's own data is fetched
     client-side only, spec §12.2's own "first paint" section) -- the SSR render therefore
     never emits the <img>, and this project's CSS-extraction pipeline only ships the scoped
     CSS for markup that actually rendered during that pass, silently dropping a plain
     `<style>` block's rules for anything that render-gated on client-only data (confirmed by
     direct inspection of the built output: Tailwind's own utility classes, generated by its
     separate static source scan, survived; this component's own hand-written `box-shadow`/
     `padding`/`background` rules did not, shipping a ring-less, padding-less crest).
     Guild.svelte's own header-art layers (the vignette, the watermark) hit the exact same
     constraint and were already built with Tailwind classes for this reason -- this
     component now matches that pattern instead of being the one exception. The ring colour
     is still per-faction/dynamic, so it stays an inline `style` (the same pattern Guild.svelte
     already uses for the per-character standing-line colour).

     Responsive by itself, no size prop: 64px at >=1024px, 44px below it (spec §12.2, "64px
     desktop, 44px phone") -- Tailwind's own default `lg:` breakpoint is exactly 1024px
     (CharacterPortrait.svelte's `XL_BOX` already resizes the same way at the same
     breakpoint), so this is plain responsive CSS, never a JS resize listener re-picking a
     prop. Padding is 16% of each size (ClassCrest.astro's own ring-recipe ratio): 7px at
     44px, 10px at 64px.

     Neutral/unknown faction (null, undefined, or anything other than 'alliance'/'horde')
     with no `src` override: renders nothing at all -- spec §12.2's own states table:
     "Absent, row is h1 alone" -- never a neutral disc the way ClassCrestRing's own
     empty-class fallback renders one (that case still needs a disc so a roster row's
     fixed-width layout holds; this row has no such constraint, and the spec's own words
     are "pixel-identical to today," which a disc would not be); preserved exactly by
     `tests/e2e/guild-centre.spec.ts`'s "a null-faction guild renders no crest" case.

     Guild crest round (docs/contracts/2026-10-05-guild-crest-api.md): an explicit `src`
     prop draws inside this same ring instead of the flat faction logo -- `guildMarkSrc`
     (web/src/lib/guild/mark.ts) is the one place that decides crest-vs-logo-vs-null, so
     this component only ever renders whatever it is handed. `src === undefined` (every
     caller before this round, and any future caller that only ever shows the flat logo)
     keeps the exact original behaviour above; `src` passed as a real URL swaps the image
     for the guild's uploaded crest without touching the ring's own faction-coloured
     box-shadow. A `null` override (guildMarkSrc's own "no crest, no faction logo" case)
     still renders nothing, matching the no-override null-faction case above -- a guild
     that is itself neutral and uncrested has no mark to ring, not a blank disc. -->
<script lang="ts">
  import { FACTION_BAR_COLOR, factionLogoSrc, type Faction } from '../../lib/faction-mark';

  let {
    faction,
    testid,
    src,
  }: { faction: Faction | null | undefined; testid?: string; src?: string | null } = $props();

  const knownFaction = $derived(faction === 'alliance' || faction === 'horde');
  const resolvedSrc = $derived(
    src !== undefined ? src : knownFaction ? factionLogoSrc(faction as Faction) : null,
  );
</script>

{#if resolvedSrc !== null}
  <img
    src={resolvedSrc}
    alt=""
    aria-hidden="true"
    width={64}
    height={64}
    loading="eager"
    decoding="async"
    class="bg-raised box-border h-11 w-11 shrink-0 rounded-full object-contain p-[7px] lg:h-16 lg:w-16 lg:p-[10px]"
    style={knownFaction ? `box-shadow: 0 0 0 2px ${FACTION_BAR_COLOR[faction as Faction]};` : ''}
    data-testid={testid}
    data-faction-name={faction ?? undefined}
  />
{/if}
