import json
from pathlib import Path

import pytest

from pipeline.manifest import newest_build
from pipeline.specs import (
    ROLES,
    SpecError,
    check_specs,
    load_specs,
    render_go,
    render_ts,
    write_specs,
)

CURATED = Path("curated")
#: The newest client build, resolved from its manifest rather than named: this
#: file is not a single-build conformance test, and a build id here would be an
#: edit waiting to be forgotten the next time a client build lands.
BUILD_DIR = Path("builds") / newest_build()

#: The one spec name that deliberately differs from the client's tree name:
#: the client calls the tree "Feral Combat", design section 2.3 calls the spec
#: Feral, and the whole site keys on `druid-feral`.
TREE_NAME_EXCEPTIONS = {"druid-feral": "Feral Combat"}


def specs():
    return load_specs(CURATED)


def test_there_is_one_spec_per_class_tree():
    records = specs()
    assert len(records) == 27
    per_class: dict[str, list[int]] = {}
    for record in records:
        per_class.setdefault(record.class_slug, []).append(record.tree_index)
    assert len(per_class) == 9
    assert all(sorted(indexes) == [0, 1, 2] for indexes in per_class.values())


def test_the_key_is_the_class_and_spec_slug():
    assert all(record.spec == f"{record.class_slug}-{record.spec_slug}" for record in specs())
    keys = [record.spec for record in specs()]
    assert len(set(keys)) == len(keys)


def test_every_slug_is_lower_kebab():
    for record in specs():
        for slug in (record.spec, record.class_slug, record.spec_slug):
            assert slug == slug.lower()
            assert " " not in slug and "_" not in slug


def test_every_role_is_one_of_the_three():
    assert {record.role for record in specs()} <= ROLES


def test_two_specs_are_the_launch_pair():
    keys = {record.spec for record in specs()}
    assert {"warrior-fury", "mage-frost"} <= keys


def test_every_class_slug_is_a_client_class():
    client = {row["slug"] for row in json.loads((BUILD_DIR / "classes.json").read_text())}
    assert {record.class_slug for record in specs()} == client


def test_every_spec_names_the_tree_at_its_index():
    """tree_index is the client's own tree position, and the name matches the
    client's tree name except for the one documented exception."""
    for record in specs():
        trees = json.loads(
            (BUILD_DIR / "talents" / f"{record.class_slug}.json").read_text()
        )["trees"]
        by_position = {tree["position"]: tree["name"] for tree in trees}
        assert record.tree_index in by_position, record.spec
        expected = TREE_NAME_EXCEPTIONS.get(record.spec, record.name)
        assert by_position[record.tree_index] == expected, record.spec


def test_a_duplicate_spec_key_is_rejected(tmp_path: Path):
    entry = {
        "spec": "warrior-fury",
        "class_slug": "warrior",
        "spec_slug": "fury",
        "name": "Fury",
        "role": "dps",
        "tree_index": 1,
    }
    (tmp_path / "specs.json").write_text(json.dumps([entry, entry]))
    with pytest.raises(SpecError, match="warrior-fury"):
        load_specs(tmp_path)


def test_a_key_that_is_not_its_two_slugs_is_rejected(tmp_path: Path):
    (tmp_path / "specs.json").write_text(
        json.dumps(
            [
                {
                    "spec": "fury",
                    "class_slug": "warrior",
                    "spec_slug": "fury",
                    "name": "Fury",
                    "role": "dps",
                    "tree_index": 1,
                }
            ]
        )
    )
    with pytest.raises(SpecError, match="fury"):
        load_specs(tmp_path)


def test_an_unknown_role_is_rejected(tmp_path: Path):
    (tmp_path / "specs.json").write_text(
        json.dumps(
            [
                {
                    "spec": "warrior-fury",
                    "class_slug": "warrior",
                    "spec_slug": "fury",
                    "name": "Fury",
                    "role": "dancer",
                    "tree_index": 1,
                }
            ]
        )
    )
    with pytest.raises(SpecError, match="dancer"):
        load_specs(tmp_path)


def test_a_missing_curated_file_is_a_clear_error(tmp_path: Path):
    with pytest.raises(SpecError, match="specs.json"):
        load_specs(tmp_path)


def test_the_generated_go_is_a_compilable_package():
    source = render_go(specs())
    assert source.startswith("// Code generated by `python -m pipeline specs`. DO NOT EDIT.")
    assert "package specs" in source
    assert 'Spec: "warrior-fury", ClassSlug: "warrior", SpecSlug: "fury"' in source
    assert source.count("\t{Spec:") == 27
    assert source.endswith("\n")


def test_the_generated_typescript_carries_the_same_rows():
    source = render_ts(specs())
    assert source.startswith("// Code generated by `python -m pipeline specs`. DO NOT EDIT.")
    assert "export const SPECS" in source
    assert "spec: 'warrior-fury'" in source
    assert source.count("  {\n") == 27
    assert source.endswith("\n")


def test_the_two_generated_files_on_disk_are_up_to_date():
    """`python -m pipeline specs` is not run by normalize, so a hand edit to
    specs.json -- or to a generated file -- that was never regenerated would
    ship a Go and a TypeScript list that disagree with the curated source.
    This is the same check `python -m pipeline specs --check` runs in CI."""
    assert check_specs(CURATED) == []


def test_check_specs_names_the_file_that_drifted(tmp_path: Path):
    go_path = tmp_path / "specs.go"
    ts_path = tmp_path / "specs.ts"
    write_specs(CURATED, go_path, ts_path)
    assert check_specs(CURATED, go_path, ts_path) == []
    ts_path.write_text(render_ts(specs()).replace("warrior-fury", "warrior-furry"))
    assert check_specs(CURATED, go_path, ts_path) == [ts_path]
    go_path.unlink()
    assert check_specs(CURATED, go_path, ts_path) == [go_path, ts_path]
