#!/usr/bin/env python3
"""Emit the client's item-set bonus rows as Go for the engine fork.

Reads the pinned build's raw client tables (ItemSet, ItemSetSpell, Spell,
SpellEffect, SpellAuraOptions, SpellMisc, SpellDuration, SpellCooldowns,
SpellName) and the loot index, and writes sim/core/client_sets_gen.go in
the fork: one row per Phase 1 set and one per spell those sets name or
trigger. The engine reads these rows to apply flat stat bonuses and to
hold every hand-written bonus to the client's amounts, so the numbers live
in one place and are never typed twice.

A set is Phase 1 when any piece, by the catalogue's set_id or by ItemSet.csv,
has a loot source that is not gated "later"
(data/curated/loot/forever-raid-phases.json).

usage: gen_set_rows.py <build dir> <fork checkout>
"""
import csv
import json
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path

OUT = "sim/core/client_sets_gen.go"


def read(path):
    with open(path, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def phase1_item_ids(loot):
    ids = set()
    for source in loot["sources"]:
        if source.get("opens") == "later":
            continue
        ids.update(source.get("items", []))
        for boss in source.get("bosses", []):
            ids.update(boss["items"])
        for trash in source.get("trash") or []:
            if isinstance(trash, dict):
                ids.update(trash.get("items", []))
    return ids


def main(build_dir, fork_dir):
    build = Path(build_dir)
    raw = build / "raw"
    loot = json.loads((build / "loot.json").read_text(encoding="utf-8"))
    obtainable = phase1_item_ids(loot)

    set_rows = {int(r["ID"]): r for r in read(raw / "ItemSet.csv")}
    set_spells = defaultdict(list)
    for r in read(raw / "ItemSetSpell.csv"):
        set_spells[int(r["ItemSetID"])].append((int(r["Threshold"]), int(r["SpellID"])))

    # A piece is any catalogue item that names the set, not only the ids
    # ItemSet.csv lists: the crafted Tier 1 pieces carry the set id on an
    # item the table does not name. PhaseOnePieces is the most slots any one
    # class can fill with a piece that has a Phase 1 source: a bonus above it
    # cannot be reached in Phase 1.
    phase1_pieces = defaultdict(int)
    for path in sorted((build / "items").glob("*.json")):
        slots = defaultdict(set)
        for item in json.loads(path.read_text(encoding="utf-8"))["items"]:
            if item.get("set_id") and item["id"] in obtainable:
                slots[item["set_id"]].add(item["slot"])
        for set_id, filled in slots.items():
            phase1_pieces[set_id] = max(phase1_pieces[set_id], len(filled))
    for set_id, row in set_rows.items():
        pieces = {int(row["ItemID_%d" % i]) for i in range(17)} - {0}
        if pieces & obtainable:
            phase1_pieces[set_id] = max(phase1_pieces[set_id], 1)
    wanted_sets = sorted(s for s in phase1_pieces if s in set_rows and set_spells[s])

    names = {int(r["ID"]): r["Name_lang"] for r in read(raw / "SpellName.csv")}
    effects = defaultdict(list)
    for r in read(raw / "SpellEffect.csv"):
        if int(r["DifficultyID"] or 0) == 0:
            effects[int(r["SpellID"])].append(r)
    aura_options = {
        int(r["SpellID"]): r
        for r in read(raw / "SpellAuraOptions.csv")
        if int(r["DifficultyID"] or 0) == 0
    }
    descriptions = {int(r["ID"]): r["Description_lang"] for r in read(raw / "Spell.csv")}
    durations = {int(r["ID"]): int(r["Duration"]) for r in read(raw / "SpellDuration.csv")}
    duration_index = {
        int(r["SpellID"]): int(r["DurationIndex"])
        for r in read(raw / "SpellMisc.csv")
        if int(r["DifficultyID"] or 0) == 0
    }
    cooldowns = {}
    for r in read(raw / "SpellCooldowns.csv"):
        if int(r["DifficultyID"] or 0) == 0:
            cooldowns[int(r["SpellID"])] = max(int(r["RecoveryTime"]), int(r["CategoryRecoveryTime"]))

    # A bonus can also name a spell only in its text ("restore $27782s1
    # Mana"): its dummy effect carries no trigger, so the text is the link.
    text_reference = re.compile(r"\$(\d{4,})[a-zA-Z]")
    spell_ids = set()
    queue = [sp for s in wanted_sets for _, sp in set_spells[s]]
    while queue:
        sp = queue.pop()
        if sp in spell_ids:
            continue
        spell_ids.add(sp)
        for e in effects[sp]:
            trigger = int(e["EffectTriggerSpell"])
            if trigger:
                queue.append(trigger)
        for referenced in text_reference.findall(descriptions.get(sp, "")):
            if int(referenced) in names:
                queue.append(int(referenced))

    lines = [
        "// Code generated by tools/gen_set_rows.py from client build %s. DO NOT EDIT." % build.name,
        "",
        "package core",
        "",
        "// clientSetRows is every Phase 1 item set the client carries (any piece with a loot",
        "// source not gated later), keyed by ItemSet id.",
        "var clientSetRows = map[int32]ClientSet{",
    ]
    for set_id in wanted_sets:
        bonuses = ", ".join(
            "{Threshold: %d, SpellID: %d}" % (t, sp) for t, sp in sorted(set_spells[set_id])
        )
        lines.append(
            "\t%d: {Name: %s, PhaseOnePieces: %d, Bonuses: []ClientSetBonus{%s}}," % (
                set_id, json.dumps(set_rows[set_id]["Name_lang"]), phase1_pieces[set_id], bonuses)
        )
    lines += [
        "}",
        "",
        "// clientSpellRows is every spell those sets name, and every spell their effects trigger.",
        "var clientSpellRows = map[int32]ClientSpell{",
    ]
    for sp in sorted(spell_ids):
        opts = aura_options.get(sp)
        chance = int(opts["ProcChance"]) if opts else 0
        internal_cooldown = int(opts["ProcCategoryRecovery"]) if opts else 0
        duration = durations.get(duration_index.get(sp, 0), 0)
        effs = []
        for e in sorted(effects[sp], key=lambda e: int(e["EffectIndex"])):
            if int(e["Effect"]) == 0:
                continue
            fields = [
                "Effect: %d" % int(e["Effect"]),
                "Aura: %d" % int(e["EffectAura"]),
                "Misc0: %d" % int(e["EffectMiscValue_0"]),
                "Misc1: %d" % int(e["EffectMiscValue_1"]),
                "Points: %s" % repr(float(e["EffectBasePointsF"])),
            ]
            if int(e["EffectTriggerSpell"]):
                fields.append("Trigger: %d" % int(e["EffectTriggerSpell"]))
            if int(e["EffectAuraPeriod"]):
                fields.append("PeriodMS: %d" % int(e["EffectAuraPeriod"]))
            masks = [int(e["EffectSpellClassMask_%d" % i]) & 0xFFFFFFFF for i in range(4)]
            if any(masks):
                fields.append("ClassMask: [4]uint32{%s}" % ", ".join(str(m) for m in masks))
            effs.append("{%s}" % ", ".join(fields))
        head = ["Name: %s" % json.dumps(names.get(sp, ""))]
        if duration > 0:
            head.append("DurationMS: %d" % duration)
        if cooldowns.get(sp):
            head.append("CooldownMS: %d" % cooldowns[sp])
        if chance and chance != 101:
            head.append("ProcChance: %d" % chance)
        if internal_cooldown:
            head.append("InternalCooldownMS: %d" % internal_cooldown)
        head.append("Effects: []ClientEffect{%s}" % ", ".join(effs))
        lines.append("\t%d: {%s}," % (sp, ", ".join(head)))
    lines += ["}", ""]
    (Path(fork_dir) / OUT).write_text("\n".join(lines), encoding="utf-8")
    subprocess.run(["gofmt", "-w", str(Path(fork_dir) / OUT)], check=True)
    print("wrote %s: %d sets, %d spells" % (OUT, len(wanted_sets), len(spell_ids)))


if __name__ == "__main__":
    if len(sys.argv) != 3:
        sys.exit(__doc__)
    main(sys.argv[1], sys.argv[2])
