// web/src/lib/sim/spec-label.ts
// Display names over the data lane's generated spec list.
//
// specs.ts is generated by `python -m pipeline specs` from data/curated/specs.json and must
// never be edited here: the contract makes that file the canonical spec list and forbids a
// second one anywhere. Its `name` is the bare spec -- "Fury", "Frost", "Beast Mastery" --
// because that is what a talent tree is called in the client. A sentence needs the class
// too, and the class's display name is already on classRows (data/builds/<build>/
// classes.json, which lib/planner/reference.ts imports for the planner), so this joins the
// two rather than carrying yet another hardcoded table of class names.
import { classRows } from '../planner/reference';
import { SPEC_BY_KEY, SPECS, type Spec } from './specs';

export function specRow(spec: string): Spec | null {
  return SPEC_BY_KEY[spec] ?? null;
}

/**
 * "Fury Warrior". The spec's own name, then its class's, which is how every player and
 * every guide says it. An unknown slug is returned unchanged rather than guessed at: a spec
 * the site has not heard of yet must still be printable.
 */
export function specLabel(spec: string): string {
  const row = specRow(spec);
  if (row === null) return spec;
  const className = classRows.find((entry) => entry.slug === row.class_slug)?.name;
  return className === undefined ? row.name : `${row.name} ${className}`;
}

/** The class slug, for classColorVar and the planner. Empty for an unknown spec. */
export function classOfSpec(spec: string): string {
  return specRow(spec)?.class_slug ?? '';
}

/**
 * The specs the simulator offers. Launch scope is Quick Sim for damage specs (design,
 * "Scope at launch"): tanks and healers are research problems and stay out of the first
 * cut, so they are filtered here rather than being absent from the canonical list.
 */
export function dpsSpecs(): readonly Spec[] {
  return SPECS.filter((row) => row.role === 'dps');
}
