// web/src/lib/sim/spec-label.ts
// Display names over the data lane's generated spec list.
//
// specs.ts is generated by `python -m pipeline specs` from data/curated/specs.json and must
// never be edited here: the contract makes that file the canonical spec list and forbids a
// second one anywhere. Its `name` is the bare spec -- "Fury", "Frost", "Beast Mastery" --
// because that is what a talent tree is called in the client. A sentence needs the class
// too, and the class's display name is already on classRows (data/builds/<build>/
// classes.json, which lib/planner/reference.ts imports for the planner), so this joins the
// two rather than carrying yet another hardcoded table of class names.
import { classRows } from '../planner/reference';
import { SPEC_BY_KEY, SPECS, type Spec } from './specs';

export function specRow(spec: string): Spec | null {
  return SPEC_BY_KEY[spec] ?? null;
}

/**
 * The spec's own display name, from the data lane's generated list -- never the slug with
 * its first letter raised, which turns `beast-mastery` into `Beast-mastery`. An unknown
 * slug falls back to itself, which is what `specRow` returning null means. Used wherever a
 * spec is named on its own, without its class (the settings bar's rotation control and the
 * rotation card); `specLabel` below is for the two-word form with the class joined in.
 */
export function specDisplayName(spec: string): string {
  return specRow(spec)?.name ?? spec;
}

/**
 * "Fury Warrior". The spec's own name, then its class's, which is how every player and
 * every guide says it. An unknown slug is returned unchanged rather than guessed at: a spec
 * the site has not heard of yet must still be printable.
 */
export function specLabel(spec: string): string {
  const row = specRow(spec);
  if (row === null) return spec;
  const className = classRows.find((entry) => entry.slug === row.class_slug)?.name;
  return className === undefined ? row.name : `${row.name} ${className}`;
}

/** The class slug, for classColorVar and the planner. Empty for an unknown spec. */
export function classOfSpec(spec: string): string {
  return specRow(spec)?.class_slug ?? '';
}

/**
 * The specs the simulator offers. Launch scope is Quick Sim for damage specs (design,
 * "Scope at launch"): tanks and healers are research problems and stay out of the first
 * cut, so they are filtered here rather than being absent from the canonical list.
 */
export function dpsSpecs(): readonly Spec[] {
  return SPECS.filter((row) => row.role === 'dps');
}

/**
 * The complement of dpsSpecs(): the 7 healer and tank specs the launch scope excludes
 * (task-2-brief.md). Filtered the same way, from the same canonical list, so the two can
 * never drift into double-counting or dropping a spec -- `/sim/specs`' "these 20 work,
 * these 7 do not" split reads both.
 */
export function nonDpsSpecs(): readonly Spec[] {
  return SPECS.filter((row) => row.role !== 'dps');
}

/**
 * Task 3 (healer review, honest round 1): the one predicate every honest-UI decision reads
 * -- RotationCard's rotation claim, RunControl's and BulkRunBar's run gate, and
 * humaniseEngineError's defensive translation all ask this, never `role === 'dps'` again
 * for themselves. Agrees with `dpsSpecs()`/`nonDpsSpecs()` by construction (the same
 * `specRow(spec)?.role === 'dps'` test, just per-spec rather than filtering the whole
 * list), so the three can never drift into disagreeing about which specs the site
 * simulates.
 *
 * Fails closed: `specRow` returns null for a spec string the canonical list does not
 * carry, and `null?.role === 'dps'` is `false` -- an unknown spec is never simulated,
 * never "true until proven otherwise".
 */
export function isSimulatedSpec(spec: string): boolean {
  return specRow(spec)?.role === 'dps';
}
