package main

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// testdata/hunter-marksmanship.json is a real, committed output of this
// command (go run ./sim/cmd/leveling-bis -spec hunter-marksmanship
// -bands 20,40,60 -weights-iterations 5 -out sim/cmd/leveling-bis/testdata),
// kept small (three bands, five weights iterations) on purpose - this
// lane's brief only asks for a fixture the schema test can round-trip,
// not a realistic nightly-quality run (that is what `make bis` writes
// to data/builds/<build>/bis, never committed from a dev machine - see
// this lane's report).
const fixturePath = "testdata/hunter-marksmanship.json"

// TestSpecReportFixtureRoundTrips is the schema test this lane's brief
// asks for: the committed fixture decodes into specReport, and
// re-encoding that value reproduces byte-identical JSON - proof the Go
// struct is a lossless, exact match for what writeSpecReport emits
// (lane bis-web's read contract), not just "close enough to decode".
func TestSpecReportFixtureRoundTrips(t *testing.T) {
	original, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixturePath, err)
	}

	var decoded specReport
	if err := json.Unmarshal(original, &decoded); err != nil {
		t.Fatalf("decoding %s into specReport: %v", fixturePath, err)
	}

	if decoded.Spec != "hunter-marksmanship" {
		t.Errorf("Spec = %q, want %q", decoded.Spec, "hunter-marksmanship")
	}
	if decoded.Build == "" {
		t.Error("Build is empty")
	}
	if decoded.EngineVersion == "" {
		t.Error("EngineVersion is empty")
	}
	if decoded.GeneratedAt == "" {
		t.Error("GeneratedAt is empty")
	}
	if len(decoded.Bands) == 0 {
		t.Fatal("Bands is empty")
	}
	for _, band := range decoded.Bands {
		if len(band.Slots) != len(slotOrder) {
			t.Errorf("band %d %s: %d slot rows, want %d (one per slotOrder entry)", band.Band, band.Faction, len(band.Slots), len(slotOrder))
		}
		if len(band.Weights) == 0 {
			t.Errorf("band %d %s: Weights is empty", band.Band, band.Faction)
		}
	}

	reencoded, err := json.MarshalIndent(decoded, "", "  ")
	if err != nil {
		t.Fatalf("re-encoding: %v", err)
	}

	var reDecoded specReport
	if err := json.Unmarshal(reencoded, &reDecoded); err != nil {
		t.Fatalf("decoding the re-encoded JSON: %v", err)
	}
	if !reflect.DeepEqual(decoded, reDecoded) {
		t.Fatal("decode -> encode -> decode did not reproduce the same value: the schema is lossy somewhere")
	}

	// Byte-identical is the stronger claim: writeSpecReport's own
	// json.MarshalIndent(out, "", "  ") call uses the same indent this
	// test does, so a fixture generated by this command's own writer
	// should re-encode to the exact bytes it was written with (modulo
	// the fixture never being re-formatted by hand).
	if string(reencoded) != string(original) {
		t.Error("re-encoding the decoded fixture did not reproduce the original bytes - either the fixture was hand-edited/reformatted, or specReport's field order/tags drifted from writeSpecReport's own output")
	}
}
