package main

import (
	"encoding/json"
	"os"
	"reflect"
	"testing"
)

// testdata/hunter-marksmanship.json is a real, committed output of this
// command (go run ./sim/cmd/leveling-bis -spec hunter-marksmanship
// -bands 20,40,60 -weights-iterations 5 -out sim/cmd/leveling-bis/testdata),
// kept small (three bands, five weights iterations) on purpose - this
// lane's brief only asks for a fixture the schema test can round-trip,
// not a realistic nightly-quality run (that is what `make bis` writes
// to data/builds/<build>/bis, never committed from a dev machine - see
// this lane's report).
const fixturePath = "testdata/hunter-marksmanship.json"

// TestSpecReportFixtureRoundTrips is the schema test this lane's brief
// asks for: the committed fixture decodes into specReport, and
// re-encoding that value reproduces byte-identical JSON - proof the Go
// struct is a lossless, exact match for what writeSpecReport emits
// (lane bis-web's read contract), not just "close enough to decode".
func TestSpecReportFixtureRoundTrips(t *testing.T) {
	original, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixturePath, err)
	}

	var decoded specReport
	if err := json.Unmarshal(original, &decoded); err != nil {
		t.Fatalf("decoding %s into specReport: %v", fixturePath, err)
	}

	if decoded.Spec != "hunter-marksmanship" {
		t.Errorf("Spec = %q, want %q", decoded.Spec, "hunter-marksmanship")
	}
	if decoded.Build == "" {
		t.Error("Build is empty")
	}
	if decoded.EngineVersion == "" {
		t.Error("EngineVersion is empty")
	}
	if decoded.GeneratedAt == "" {
		t.Error("GeneratedAt is empty")
	}
	if len(decoded.Bands) == 0 {
		t.Fatal("Bands is empty")
	}
	for _, band := range decoded.Bands {
		if len(band.Slots) != len(slotOrder) {
			t.Errorf("band %d %s: %d slot rows, want %d (one per slotOrder entry)", band.Band, band.Faction, len(band.Slots), len(slotOrder))
		}
		if len(band.Weights) == 0 {
			t.Errorf("band %d %s: Weights is empty", band.Band, band.Faction)
		}
	}

	reencoded, err := json.MarshalIndent(decoded, "", "  ")
	if err != nil {
		t.Fatalf("re-encoding: %v", err)
	}

	var reDecoded specReport
	if err := json.Unmarshal(reencoded, &reDecoded); err != nil {
		t.Fatalf("decoding the re-encoded JSON: %v", err)
	}
	if !reflect.DeepEqual(decoded, reDecoded) {
		t.Fatal("decode -> encode -> decode did not reproduce the same value: the schema is lossy somewhere")
	}

	// Byte-identical is the stronger claim: writeSpecReport's own
	// json.MarshalIndent(out, "", "  ") call uses the same indent this
	// test does, so a fixture generated by this command's own writer
	// should re-encode to the exact bytes it was written with (modulo
	// the fixture never being re-formatted by hand).
	if string(reencoded) != string(original) {
		t.Error("re-encoding the decoded fixture did not reproduce the original bytes - either the fixture was hand-edited/reformatted, or specReport's field order/tags drifted from writeSpecReport's own output")
	}
}

// TestPublishedRatingFamilyWeightRowsSatisfyTheirOwnContract is this
// lane's brief, item 3's own contract test: for every published
// rating-family row (RatingFactor set), Weight == WeightPerPercent /
// RatingFactor must hold exactly - the row's own numbers must be
// internally consistent, not just individually plausible. Run
// directly against the committed fixture (regenerated by this lane so
// it already carries these fields), so this is also a regression test
// against a real run's own output, not only a hand-built unit case.
func TestPublishedRatingFamilyWeightRowsSatisfyTheirOwnContract(t *testing.T) {
	b, err := os.ReadFile(fixturePath)
	if err != nil {
		t.Fatalf("reading %s: %v", fixturePath, err)
	}
	var decoded specReport
	if err := json.Unmarshal(b, &decoded); err != nil {
		t.Fatalf("decoding %s: %v", fixturePath, err)
	}
	checked := 0
	for _, band := range decoded.Bands {
		for _, w := range band.Weights {
			if w.RatingFactor == 0 {
				continue
			}
			if w.Unit != "rating" {
				t.Errorf("band %d %s stat %s: rating_factor set but unit = %q, want \"rating\"", band.Band, band.Faction, w.Stat, w.Unit)
			}
			want := w.WeightPerPercent / w.RatingFactor
			if w.Weight != want {
				t.Errorf("band %d %s stat %s: weight = %v, want weight_per_percent/rating_factor = %v", band.Band, band.Faction, w.Stat, w.Weight, want)
			}
			checked++
		}
	}
	if checked == 0 {
		t.Fatal("no rating-family weight row (rating_factor set) found in the fixture - the fixture no longer exercises this contract")
	}
}

// TestPublishWeightRatingUnitsConvertsOnlyRatingFamilyRows is the
// function-level unit test alongside the fixture-level contract test
// above: a hand-built row set pins the exact conversion (weight AND
// error divide by the factor, weight_per_percent keeps the original)
// and that a non-rating-family stat passes through with
// weight_per_percent set but unit/rating_factor left unset.
func TestPublishWeightRatingUnitsConvertsOnlyRatingFamilyRows(t *testing.T) {
	rows := []weightRow{
		{Stat: "crit", Weight: 18.2, Error: 3.5, Insignificant: false},
		{Stat: "agility", Weight: 2.0, Error: 0.1, Insignificant: false},
	}
	factors := ratingFactors{"crit": 14, "hit": 10}

	got := publishWeightRatingUnits(rows, factors)

	crit := got[0]
	if crit.Unit != "rating" || crit.RatingFactor != 14 {
		t.Errorf("crit row = %+v, want unit=rating rating_factor=14", crit)
	}
	if crit.Weight != 18.2/14 || crit.Error != 3.5/14 {
		t.Errorf("crit row weight/error = %v/%v, want %v/%v", crit.Weight, crit.Error, 18.2/14, 3.5/14)
	}
	if crit.WeightPerPercent != 18.2 {
		t.Errorf("crit row weight_per_percent = %v, want the original sim-unit weight 18.2", crit.WeightPerPercent)
	}

	agility := got[1]
	if agility.Unit != "" || agility.RatingFactor != 0 {
		t.Errorf("agility row = %+v, want no unit/rating_factor (not a rating-family stat)", agility)
	}
	if agility.Weight != 2.0 || agility.WeightPerPercent != 2.0 {
		t.Errorf("agility row weight/weight_per_percent = %v/%v, want 2.0/2.0 (unchanged)", agility.Weight, agility.WeightPerPercent)
	}

	// Immutability: the input slice's own rows are untouched.
	if rows[0].Weight != 18.2 || rows[0].Unit != "" {
		t.Errorf("publishWeightRatingUnits mutated its input: %+v", rows[0])
	}
}
