package main

import (
	"fmt"
	"strings"
	"time"
)

// report is one spec's whole rotation-search run, rendered to
// markdown.
type report struct {
	opts      options
	in        inputs
	baseline  estimate
	probe     []probeRow
	probeOnly bool
	best      rotation
	bestEst   estimate
	accepted  []acceptedMutation
	names     map[int]string
	elapsed   time.Duration
}

func (r report) markdown() string {
	var b strings.Builder
	spec := r.in.setup.spec
	fmt.Fprintf(&b, "# Rotation search: %s, level %d\n\n", spec.Name, r.opts.level)
	fmt.Fprintf(&b, "Generated by `sim/cmd/rotation-search` against client %s. Gear and talents: the committed level-%d %s BiS band's gear and the guide's own FS1 build, both held fixed - only the rotation varies. Seed %d (the same for every sim). Run time %s.\n\n",
		r.in.clientBuild, r.opts.level, r.opts.faction, r.opts.seed, r.elapsed.Round(time.Second))
	fmt.Fprintf(&b, "Baseline (the curated rotation): **%.1f ± %.1f DPS** (%d iterations).\n\n", r.baseline.Mean, r.baseline.Err, r.opts.confirmIterations)
	b.WriteString("**Caveat:** this sims one solo character with no raid around it. A group utility totem, aura, or buff (Windfury Totem, Strength of Earth) can measure as a pure DPS loss here purely because this character is the only one who would benefit from the GCD spent refreshing it - the real payoff is the melee group standing in it, which a solo sim cannot see. Treat any finding that drops a group buff/totem line as a hint to verify by hand, not a rotation change to paste blind.\n\n")

	r.writeProbe(&b)
	if r.probeOnly {
		return b.String()
	}
	r.writeVerdict(&b)
	r.writeAccepted(&b)
	r.writeDanglingGates(&b)
	r.writeRotations(&b)
	r.writeWinnerJSON(&b)
	return b.String()
}

func (r report) writeVerdict(b *strings.Builder) {
	delta := r.bestEst.Mean - r.baseline.Mean
	err := combinedErr(r.bestEst, r.baseline)
	switch {
	case delta > err:
		fmt.Fprintf(b, "**Verdict: the search found a better rotation, %+.1f DPS (%+.1f%%), beyond the combined error ±%.1f.** Baseline %.1f ± %.1f, best %.1f ± %.1f (%d iterations).\n\n",
			delta, 100*delta/r.baseline.Mean, err, r.baseline.Mean, r.baseline.Err, r.bestEst.Mean, r.bestEst.Err, r.opts.confirmIterations)
	default:
		fmt.Fprintf(b, "**Verdict: the curated rotation is already the best found.** Best variant %+.1f DPS (±%.1f combined), within error.\n\n", delta, err)
	}
}

func (r report) writeProbe(b *strings.Builder) {
	b.WriteString("## Action probe (step 2: is the rotation right for the talents?)\n\n")
	b.WriteString("Each row is one sim at the confirm iteration count against the baseline. A **removal** row sims the rotation with that action taken out; a positive delta means the action helps (removing it costs DPS) - a negative delta beyond error means the action hurts and is a wrong line. An **insertion** row sims the rotation with that learned-but-uncast spell added at the top with a default condition; a positive delta beyond error means it is a missing line.\n\n")
	b.WriteString("| Kind | Action / spell | Delta DPS | ± | Verdict |\n|---|---|---|---|---|\n")
	for _, row := range r.probe {
		if row.Verdict == verdictError {
			fmt.Fprintf(b, "| %s | %s | - | - | %s: %s |\n", row.Kind, row.Label, row.Verdict, firstLine(row.Error))
			continue
		}
		fmt.Fprintf(b, "| %s | %s | %+.1f | %.1f | %s |\n", row.Kind, row.Label, row.Delta, row.Err, row.Verdict)
	}
	b.WriteString("\n")
	wrong, missing := r.wrongAndMissing()
	if len(wrong) == 0 && len(missing) == 0 {
		b.WriteString("No wrong lines and no missing lines beyond the combined error.\n\n")
		return
	}
	if len(wrong) > 0 {
		fmt.Fprintf(b, "**Wrong lines** (removing them raises DPS beyond error): %s\n\n", strings.Join(wrong, ", "))
	}
	if len(missing) > 0 {
		fmt.Fprintf(b, "**Missing lines** (inserting them raises DPS beyond error): %s\n\n", strings.Join(missing, ", "))
	}
}

func (r report) wrongAndMissing() (wrong, missing []string) {
	for _, row := range r.probe {
		if row.Kind == "remove" && row.Verdict == verdictHurts {
			wrong = append(wrong, row.Label)
		}
		if row.Kind == "insert" && row.Verdict == verdictHelps {
			missing = append(missing, row.Label)
		}
	}
	return wrong, missing
}

func (r report) writeAccepted(b *strings.Builder) {
	b.WriteString("## Search: accepted mutations (step 3)\n\n")
	if len(r.accepted) == 0 {
		b.WriteString("No mutation beat the incumbent beyond the combined error at the screening iteration count; the baseline rotation is the search's own best.\n\n")
		return
	}
	b.WriteString("| Round | Mutation | Gain | ± |\n|---|---|---|---|\n")
	for _, a := range r.accepted {
		fmt.Fprintf(b, "| %d | %s | %+.1f | %.1f |\n", a.Round, a.Label, a.Gain, a.GainErr)
	}
	b.WriteString("\n")
}

// writeDanglingGates flags a known sharp edge of the greedy search: a
// round only measures the rotation its own mutation produces, so
// removing the one line that applies a dot or aura can leave a LATER
// line's presence gate (a bare dotIsActive/auraIsActive, such as Lava
// Burst's own "while Flame Shock is up" condition) permanently false
// - a legal, harmless, but dead line the search's own DPS measurement
// already priced in (a dead line costs nothing further), which a
// curation lane should look at by hand rather than paste blind.
func (r report) writeDanglingGates(b *strings.Builder) {
	dangling := danglingGates(r.best, r.names)
	if len(dangling) == 0 {
		return
	}
	b.WriteString("## Dangling gates in the winning rotation\n\n")
	b.WriteString("These lines gate on a dot or aura that nothing else in the winning rotation ever applies, so they are legal but dead (never fire). The search's own measurement already reflects this - a dead line costs nothing - but a curation lane should decide by hand whether to drop the line or restore whatever used to apply its gate.\n\n")
	for _, d := range dangling {
		fmt.Fprintf(b, "- %s\n", d)
	}
	b.WriteString("\n")
}

func danglingGates(r rotation, names map[int]string) []string {
	cast := authoredCastIDs(r)
	var out []string
	for _, e := range r.PriorityList {
		cond, ok := e.Action["condition"]
		if !ok {
			continue
		}
		var gates []actionID
		findBareActiveGates(cond, &gates)
		for _, g := range gates {
			if !cast[g.SpellID] {
				out = append(out, fmt.Sprintf("%s requires %s, which nothing in this rotation casts", entryActionLabel(e.Action, names), spellLabel(names, g.SpellID, g.Rank)))
			}
		}
	}
	return out
}

func (r report) writeRotations(b *strings.Builder) {
	b.WriteString("## Rotation, baseline vs winner\n\n")
	b.WriteString("| # | Baseline | Winner |\n|---|---|---|\n")
	base := r.in.base.PriorityList
	best := r.best.PriorityList
	n := len(base)
	if len(best) > n {
		n = len(best)
	}
	for i := 0; i < n; i++ {
		baseCell, bestCell := "-", "-"
		if i < len(base) {
			baseCell = renderEntry(base[i], r.names)
		}
		if i < len(best) {
			bestCell = renderEntry(best[i], r.names)
		}
		fmt.Fprintf(b, "| %d | %s | %s |\n", i+1, baseCell, bestCell)
	}
	b.WriteString("\n")
}

func (r report) writeWinnerJSON(b *strings.Builder) {
	b.WriteString("## Winning rotation, engine APL JSON\n\n")
	b.WriteString("Paste this into `data/curated/apl/" + r.in.setup.spec.Spec + ".json`'s `rotation` field (never edited directly by this tool):\n\n")
	b.WriteString("```json\n")
	j, err := r.best.marshalIndent()
	if err != nil {
		fmt.Fprintf(b, "(failed to render: %v)\n", err)
	} else {
		b.Write(j)
		b.WriteString("\n")
	}
	b.WriteString("```\n")
}

// firstLine is a sim error's first line only - a panic the engine
// recovers from (see search.go's runParallel doc) carries its whole
// goroutine stack trace in the error text, which is useful in a
// terminal but would blow up a markdown table cell across dozens of
// lines; the first line alone ("the sim failed: ... runtime error:
// invalid memory address ...") already says what broke.
func firstLine(s string) string {
	if i := strings.IndexByte(s, '\n'); i >= 0 {
		return s[:i]
	}
	return s
}
